import {Route} from "@/app/static/routing";

const LANGUAGE = {
    'ab-GE': 'Abkhazian',
    'aa-ET': 'Afar',
    'af-ZA': 'Afrikaans',
    'ak-GH': 'Akan',
    'sq-AL': 'Albanian',
    'am-ET': 'Amharic',
    'ar-SA': 'Arabic',
    'an-ES': 'Aragonese',
    'hy-AM': 'Armenian',
    'as-IN': 'Assamese',
    'av-RU': 'Avaric',
    'ae-IR': 'Avestan',
    'ay-BO': 'Aymara',
    'az-AZ': 'Azerbaijani',
    'bm-ML': 'Bambara',
    'ba-RU': 'Bashkir',
    'eu-ES': 'Basque',
    'be-BY': 'Belarusian',
    'fr-BE': 'Belgian French',
    'bn-BD': 'Bengali',
    'bh-IN': 'Bihari',
    'bi-VU': 'Bislama',
    'bs-YU': 'Bosnian',
    'pt-BR': 'Brazilian Portuguese',
    'br-FR': 'Breton',
    'bg-BG': 'Bulgarian',
    'my-MM': 'Burmese',
    'fr-CA': 'Canadian French',
    'ca-ES': 'Catalan',
    'ch-GU': 'Chamorro',
    'ce-RU': 'Chechen',
    'ny-MW': 'Chichewa',
    'cu-RU': 'Church Slavic',
    'cv-RU': 'Chuvash',
    'kw-GB': 'Cornish',
    'co-FR': 'Corsican',
    'cr-CA': 'Cree',
    'hr-HR': 'Croatian',
    'cs-CZ': 'Czech',
    'da-DK': 'Danish',
    'dv-MV': 'Divehi',
    'nl-NL': 'Dutch',
    'dz-BT': 'Dzongkha',
    'en-US': 'English (US)',
    'en-AU': 'English (Australian)',
    'en-GB': 'English (UK)',
    'eo-FR': 'Esperanto',
    'et-EE': 'Estonian',
    'ee-GH': 'Ewe',
    'fo-FO': 'Faroese',
    'fj-FJ': 'Fijian',
    'fi-FI': 'Finnish',
    'nl-BE': 'Flemish',
    'fr-FR': 'French',
    'fr-CH': 'French (Switzerland)',
    'fy-NL': 'Frisian',
    'ff-NG': 'Fulah',
    'gl-ES': 'Gallegan',
    'lg-UG': 'Ganda',
    'ka-GE': 'Georgian',
    'de-DE': 'German',
    'de-AT': 'German (Austria)',
    'de-CH': 'German (Switzerland)',
    'el-GR': 'Greek, Modern (1453-)',
    'kl-GL': 'Greenlandic',
    'gn-PY': 'Guarani',
    'gu-IN': 'Gujarati',
    'ht-HT': 'Haitian',
    'ha-NG': 'Hausa',
    'he-IL': 'Hebrew',
    'hz-NA': 'Herero',
    'hi-IN': 'Hindi',
    'ho-PG': 'Hiri Motu',
    'hu-HU': 'Hungarian',
    'is-IS': 'Icelandic',
    'io-FR': 'Ido',
    'ig-NG': 'Igbo',
    'id-ID': 'Indonesian',
    'ia-FR': 'Interlingua',
    'ie': 'Interlingue',
    'iu-CA': 'Inuktitut',
    'ik-US': 'Inupiaq',
    'ga-IE': 'Irish',
    'it-IT': 'Italian',
    'it-CH': 'Italian (Switzerland)',
    'ja-JP': 'Japanese',
    'jv-ID': 'Javanese',
    'kn-IN': 'Kannada',
    'kr-NG': 'Kanuri',
    'ks-IN': 'Kashmiri',
    'kk-KZ': 'Kazakh',
    'km-KH': 'Khmer',
    'ki-KE': 'Kikuyu',
    'rw-RW': 'Kinyarwanda',
    'ky-KG': 'Kirghiz',
    'kv-RU': 'Komi',
    'kg-CD': 'Kongo',
    'ko-KR': 'Korean',
    'kj-AO': 'Kuanyama',
    'ku-IQ': 'Kurdish',
    'lo-LA': 'Lao',
    'la-VA': 'Latin',
    'lv-LV': 'Latvian',
    'lb-LU': 'Letzeburgesch',
    'li-NL': 'Limburgan',
    'ln-CD': 'Lingala',
    'lt-LT': 'Lithuanian',
    'lu-CD': 'Luba - Katanga',
    'mk-MK': 'Macedonian',
    'mg-MG': 'Malagasy',
    'ms-MY': 'Malay',
    'ml-IN': 'Malayalam',
    'mt-MT': 'Maltese',
    'gv-GB': 'Manx',
    'mi-NZ': 'Maori',
    'mr-IN': 'Marathi',
    'mh-MH': 'Marshallese',
    'es-MX': 'Mexican Spanish',
    'mo-MD': 'Moldavian',
    'mn-MN': 'Mongolian',
    'na-NR': 'Nauru',
    'nv-US': 'Navajo',
    'nd-ZW': 'Ndebele, North',
    'nr-ZA': 'Ndebele, South',
    'ng-NA': 'Ndonga',
    'ne-NP': 'Nepali',
    'se-NO': 'Northern Sami',
    'no-NO': 'Norwegian',
    'nb-NO': 'Norwegian Bokmal',
    'nn-NO': 'Norwegian Nynorsk',
    'oc-FR': 'Occitan (post 1500)',
    'oj-CA': 'Ojibwa',
    'or-IN': 'Oriya',
    'om-ET': 'Oromo',
    'os-GE': 'Ossetian',
    'pi-IN': 'Pali',
    'pa-IN': 'Panjabi',
    'fa-IR': 'Persian',
    'pl-PL': 'Polish',
    'pt-PT': 'Portuguese',
    'ps-AF': 'Pushto',
    'qu-PE': 'Quechua',
    'rm-CH': 'Raeto-Romance',
    'ro-RO': 'Romanian',
    'rn-BI': 'Rundi',
    'ru-RU': 'Russian',
    'sm-WS': 'Samoan',
    'sg-CF': 'Sango',
    'sa-IN': 'Sanskrit',
    'sc-IT': 'Sardinian',
    'gd-GB': 'Scottish Gaelic',
    'sr-SP': 'Serbian',
    'sn-ZW': 'Shona',
    'ii-CN': 'Sichuan Yi',
    'zh-CN': 'Simplified Chinese',
    'sd-PK': 'Sindhi',
    'si-LK': 'Sinhalese',
    'sk-SK': 'Slovak',
    'sl-SI': 'Slovenian',
    'so-SO': 'Somali',
    'st-LS': 'Sotho, Southern',
    'es-ES': 'Spanish',
    'su-ID': 'Sundanese',
    'sw-TZ': 'Swahili',
    'ss-SZ': 'Swati',
    'sv-SE': 'Swedish',
    'tl-PH': 'Tagalog',
    'ty-PF': 'Tahitian',
    'tg-TJ': 'Tajik',
    'ta-IN': 'Tamil',
    'tt-RU': 'Tatar',
    'te-IN': 'Telugu',
    'th-TH': 'Thai',
    'bo-CN': 'Tibetan',
    'ti-ET': 'Tigrinya',
    'to-TO': 'Tonga (Tonga Islands)',
    'zh-TW': 'Traditional Chinese',
    'ts-ZA': 'Tsonga',
    'tn-BW': 'Tswana',
    'tr-TR': 'Turkish',
    'tk-TM': 'Turkmen',
    'tw-GH': 'Twi',
    'ug-CN': 'Uighur',
    'uk-UA': 'Ukrainian',
    'ur-PK': 'Urdu',
    'uz-UZ': 'Uzbek',
    've-ZA': 'Venda',
    'vi-VN': 'Vietnamese',
    'vo': 'Volapük',
    'wa-BE': 'Walloon',
    'cy-GB': 'Welsh',
    'wo-SN': 'Wolof',
    'xh-ZA': 'Xhosa',
    'yi-IL': 'Yiddish',
    'yo-NG': 'Yoruba',
    'za-CN': 'Zhuang',
    'zu-ZA': 'Zulu',
}
type LanguageKey = keyof typeof LANGUAGE;

const SALUTATION = {
    'DR': 'Dr.',
    'MISS': 'Miss',
    'MR': 'Mr.',
    'MRS': 'Mrs.',
    'MS': 'Ms.',
}
type SalutationKey = keyof typeof SALUTATION;


const LAYOUT: { fadeDuration: number; profileLinks: Route[] } = {
    fadeDuration: 500,
    profileLinks: [Route.MyTern, Route.Profile, Route.Billing],
}

const MAPPED_NAV_ROUTES: Record<string, string> = {
    [Route.Products]: 'Products',
    [Route.Services]: 'Services',
    [Route.TernKey]: 'TernKey',

}

const MAPPED_SUB_NAV_ROUTES: Record<string, string> = {
    [Route.Products]: '/All',
    [Route.TernKey]: '/Application',
    [Route.Dot]: '/Download',
    [Route.Services]: '/ARCH',
    [Route.TBD0]: '/TBD',
    [Route.TBD1]: '/TBD',
    [Route.TBD2]: '/TBD',
}

const MERGED_SUB_NAV_ROUTES: string[] = [Route.TernKey];
const ALWAYS_MAPPED_ROUTES: string[] = ['TBD', 'arch'];


export type  {SalutationKey, LanguageKey};
export {
    MAPPED_NAV_ROUTES,
    MERGED_SUB_NAV_ROUTES,
    ALWAYS_MAPPED_ROUTES,
    MAPPED_SUB_NAV_ROUTES,
    LANGUAGE,
    SALUTATION,
    LAYOUT
};
