import { KeysOfUnion } from '@/app/types/utils';
import { Address, Phone } from '@/app/contexts/user.context';

const COUNTRY = {
    '': '',
    US: 'United States of America',
    AF: 'Afghanistan',
    AX: 'Åland Islands',
    AL: 'Albania',
    DZ: 'Algeria',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua and Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia, Plurinational State of',
    BQ: 'Bonaire, Sint Eustatius and Saba',
    BA: 'Bosnia and Herzegovina',
    BW: 'Botswana',
    BV: 'Bouvet Island',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    BN: 'Brunei Darussalam',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CD: 'Congo, The Democratic Republic of the',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: "Côte d'Ivoire",
    HR: 'Croatia',
    CW: 'Curaçao',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EE: 'Estonia',
    SZ: 'Eswatini',
    ET: 'Ethiopia',
    FK: 'Falkland Islands (Malvinas)',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HM: 'Heard Island and McDonald Islands',
    VA: 'Holy See (Vatican City State)',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    KR: 'Korea, Republic of',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: "Lao People's Democratic Republic",
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia, Federated States of',
    MD: 'Moldova, Republic of',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    MK: 'North Macedonia',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestine, State of',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RW: 'Rwanda',
    BL: 'Saint Barthélemy',
    SH: 'Saint Helena, Ascension and Tristan da Cunha',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    MF: 'Saint Martin (French Part)',
    PM: 'Saint Pierre and Miquelon',
    VC: 'Saint Vincent and the Grenadines',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Sao Tome and Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten (Dutch part)',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SE: 'Sweden',
    CH: 'Switzerland',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania, United Republic of',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TN: 'Tunisia',
    TR: 'Türkiye',
    TM: 'Turkmenistan',
    TC: 'Turks and Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    UM: 'United States Minor Outlying Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VE: 'Venezuela, Bolivarian Republic of',
    VN: 'Viet Nam',
    VG: 'Virgin Islands, British',
    VI: 'Virgin Islands, U.S.',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
};

const STATE_PROVINCE: Record<CountryKey, Record<string, string>> = {
    '': { ' ': ' ' },
    AF: {
        BDS: 'Badakhshan',
        BDG: 'Badghis',
        BGL: 'Baghlan',
        BAL: 'Balkh',
        BAM: 'Bamyan',
        DAY: 'Daykundi',
        FRA: 'Farah',
        FYB: 'Faryab',
        GHA: 'Ghazni',
        GHO: 'Ghor',
        HEL: 'Helmand',
        HER: 'Herat',
        JOW: 'Jowzjan',
        KAB: 'Kabul',
        KAN: 'Kandahar',
        KAP: 'Kapisa',
        KHO: 'Khost',
        KNR: 'Kunar',
        KDZ: 'Kunduz',
        LAG: 'Laghman',
        LOG: 'Logar',
        NAN: 'Nangarhar',
        NIM: 'Nimruz',
        NUR: 'Nuristan',
        PAN: 'Panjshir',
        PAR: 'Parwan',
        SAM: 'Samangan',
        SAR: 'Sar-e Pol',
        TAK: 'Takhar',
        URU: 'Uruzgan',
        WAR: 'Wardak',
        ZAB: 'Zabul',
    },
    AX: {
        BRA: 'Brändö',
        ECK: 'Eckerö',
        FIN: 'Finström',
        FOG: 'Föglö',
        GET: 'Geta',
        HAM: 'Hammarland',
        JOM: 'Jomala',
        KUM: 'Kumlinge',
        KOK: 'Kökar',
        LEM: 'Lemland',
        LUM: 'Lumparland',
        MAR: 'Mariehamn',
        SAL: 'Saltvik',
        SOT: 'Sottunga',
        SUN: 'Sund',
        VAR: 'Vårdö',
    },
    AL: {
        '01': 'Berat',
        '09': 'Dibër',
        '02': 'Durrës',
        '03': 'Elbasan',
        '04': 'Fier',
        '05': 'Gjirokastër',
        '06': 'Korçë',
        '07': 'Kukës',
        '08': 'Lezhë',
        '10': 'Shkodër',
        '11': 'Tiranë',
        '12': 'Vlorë',
    },
    DZ: {
        '01': 'Adrar',
        '16': 'Alger',
        '23': 'Annaba',
        '44': 'Aïn Defla',
        '46': 'Aïn Témouchent',
        '05': 'Batna',
        '07': 'Biskra',
        '09': 'Blida',
        '50': 'Bordj Badji Mokhtar',
        '34': 'Bordj Bou Arréridj',
        '10': 'Bouira',
        '35': 'Boumerdès',
        '08': 'Béchar',
        '06': 'Béjaïa',
        '52': 'Béni Abbès',
        '02': 'Chlef',
        '25': 'Constantine',
        '56': 'Djanet',
        '17': 'Djelfa',
        '32': 'El Bayadh',
        '58': 'El Meniaa',
        '57': 'El M’Ghair',
        '39': 'El Oued',
        '36': 'El Tarf',
        '47': 'Ghardaïa',
        '24': 'Guelma',
        '33': 'Illizi',
        '54': 'In Guezzam',
        '53': 'In Salah',
        '18': 'Jijel',
        '40': 'Khenchela',
        '03': 'Laghouat',
        '29': 'Mascara',
        '43': 'Mila',
        '27': 'Mostaganem',
        '26': 'Médéa',
        '28': 'M’Sila',
        '45': 'Naâma',
        '31': 'Oran',
        '30': 'Ouargla',
        '51': 'Ouled Djellal',
        '04': 'Oum El Bouaghi',
        '48': 'Relizane',
        '20': 'Saïda',
        '22': 'Sidi Bel Abbès',
        '21': 'Skikda',
        '41': 'Souk Ahras',
        '19': 'Sétif',
        '11': 'Tamanrasset',
        '14': 'Tiaret',
        '49': 'Timimoun',
        '37': 'Tindouf',
        '42': 'Tipaza',
        '38': 'Tissemsilt',
        '15': 'Tizi Ouzou',
        '13': 'Tlemcen',
        '55': 'Touggourt',
        '12': 'Tébessa',
    },
    AS: {
        E: 'Eastern District',
        M: 'Manu‘a District',
        R: 'Rose Atoll',
        S: 'Swains Island',
        W: 'Western District',
    },
    AD: {
        '07': 'Andorra la Vella',
        '02': 'Canillo',
        '03': 'Encamp',
        '08': 'Escaldes-Engordany',
        '04': 'La Massana',
        '05': 'Ordino',
        '06': 'Sant Julià de Lòria',
    },
    AO: {
        BGO: 'Bengo',
        BGU: 'Benguela',
        BIE: 'Bié',
        CAB: 'Cabinda',
        CCU: 'Cuando Cubango',
        CNO: 'Cuanza Norte',
        CUS: 'Cuanza Sul',
        CNN: 'Cunene',
        HUA: 'Huambo',
        HUI: 'Huíla',
        LUA: 'Luanda',
        LNO: 'Lunda Norte',
        LSU: 'Lunda Sul',
        MAL: 'Malanje',
        MOX: 'Moxico',
        NAM: 'Namibe',
        UIG: 'Uíge',
        ZAI: 'Zaire',
    },
    AI: {
        AN: 'Anguilla',
    },
    AQ: {
        AN: 'Antarctica',
    },
    AG: {
        '10': 'Barbuda',
        '11': 'Redonda',
        '03': 'Saint George',
        '04': 'Saint John',
        '05': 'Saint Mary',
        '06': 'Saint Paul',
        '07': 'Saint Peter',
        '08': 'Saint Philip',
    },
    AR: {
        B: 'Buenos Aires',
        K: 'Catamarca',
        H: 'Chaco',
        U: 'Chubut',
        C: 'Ciudad Autónoma de Buenos Aires',
        W: 'Corrientes',
        X: 'Córdoba',
        E: 'Entre Ríos',
        P: 'Formosa',
        Y: 'Jujuy',
        L: 'La Pampa',
        F: 'La Rioja',
        M: 'Mendoza',
        N: 'Misiones',
        Q: 'Neuquén',
        R: 'Río Negro',
        A: 'Salta',
        J: 'San Juan',
        D: 'San Luis',
        Z: 'Santa Cruz',
        S: 'Santa Fe',
        G: 'Santiago del Estero',
        V: 'Tierra del Fuego',
        T: 'Tucumán',
    },
    AM: {
        AG: 'Aragatsotn',
        AR: 'Ararat',
        AV: 'Armavir',
        GR: 'Gegharkunik',
        KT: 'Kotayk',
        LO: 'Lori',
        SH: 'Shirak',
        SU: 'Syunik',
        TV: 'Tavush',
        VD: 'Vayots Dzor',
        ER: 'Yerevan',
    },
    AW: {
        NO: 'Noord/Tanki Leendert',
        OR: 'Oranjestad East',
        OE: 'Oranjestad West',
        PA: 'Paradera',
        SN: 'San Nicolas North',
        SS: 'San Nicolas South',
        SI: 'Santa Cruz',
        SA: 'Savaneta',
    },
    AU: {
        ACT: 'Australian Capital Territory',
        CX: 'Christmas Island',
        CC: 'Cocos (Keeling) Islands',
        HM: 'Heard Island and McDonald Islands',
        NSW: 'New South Wales',
        NF: 'Norfolk Island',
        NT: 'Northern Territory',
        QLD: 'Queensland',
        SA: 'South Australia',
        TAS: 'Tasmania',
        VIC: 'Victoria',
        WA: 'Western Australia',
    },
    AT: {
        '1': 'Burgenland',
        '2': 'Kärnten (Carinthia)',
        '3': 'Niederösterreich (Lower Austria)',
        '4': 'Oberösterreich (Upper Austria)',
        '5': 'Salzburg',
        '6': 'Steiermark (Styria)',
        '7': 'Tirol (Tyrol)',
        '8': 'Vorarlberg',
        '9': 'Wien (Vienna)',
    },
    AZ: {
        ABS: 'Abşeron',
        AST: 'Astara',
        AGC: 'Ağcabədi',
        AGD: 'Ağdaş',
        AGA: 'Ağstafa',
        AGU: 'Ağsu',
        BA: 'Bakı (Baku)',
        BAL: 'Balakən',
        BEY: 'Beyləqan',
        BIL: 'Biləsuvar',
        BAR: 'Bərdə',
        CAB: 'Cəbrayıl',
        CAL: 'Cəlilabad',
        DAS: 'Daşkəsən',
        FUZ: 'Füzuli',
        GOR: 'Goranboy',
        GOY: 'Göyçay',
        GAD: 'Gədəbəy',
        GA: 'Gəncə (Ganja)',
        HAC: 'Hacıqabul',
        KUR: 'Kürdəmir',
        KAL: 'Kəlbəcər',
        LER: 'Lerik',
        LA: 'Lənkəran (City)',
        LAN: 'Lənkəran (District)',
        MAS: 'Masallı',
        NA: 'Naftalan (City)',
        NX: 'Naxçıvan (Autonomous Republic)',
        IMI: 'İmişli',
        ISM: 'İsmayıllı',
    },
    BS: {
        AK: 'Acklins',
        BY: 'Berry Islands',
        BI: 'Bimini',
        BP: 'Black Point',
        CI: 'Cat Island',
        CO: 'Central Abaco',
        CS: 'Central Andros',
        CE: 'Central Eleuthera',
        CK: 'Crooked Island and Long Cay',
        EG: 'East Grand Bahama',
        EX: 'Exuma',
        FP: 'Freeport',
        GC: 'Grand Cay',
        GH: 'Green Turtle Cay',
        HI: 'Harbour Island',
        HT: 'Hope Town',
        IN: 'Inagua',
        LI: 'Long Island',
        MC: 'Mangrove Cay',
        MG: 'Mayaguana',
        MI: 'Moore’s Island',
        NP: 'New Providence',
        NO: 'North Abaco',
        NS: 'North Andros',
        NE: 'North Eleuthera',
        RI: 'Ragged Island',
        RC: 'Rum Cay',
        SS: 'San Salvador',
        SO: 'South Abaco',
        SA: 'South Andros',
        SE: 'South Eleuthera',
        WG: 'West Grand Bahama',
    },
    BH: {
        '13': 'Capital',
        '14': 'Muharraq',
        '15': 'Northern',
        '17': 'Southern',
    },
    BD: {
        '01': 'Barishal',
        '02': 'Chattogram',
        '03': 'Dhaka',
        '04': 'Khulna',
        '08': 'Mymensingh',
        '05': 'Rajshahi',
        '06': 'Rangpur',
        '07': 'Sylhet',
    },
    BB: {
        '01': 'Christ Church',
        '02': 'Saint Andrew',
        '03': 'Saint George',
        '04': 'Saint James',
        '05': 'Saint John',
        '06': 'Saint Joseph',
        '07': 'Saint Lucy',
        '08': 'Saint Michael',
        '09': 'Saint Peter',
        '10': 'Saint Philip',
        '11': 'Saint Thomas',
    },
    BE: {
        VAN: 'Antwerp',
        BRU: 'Brussels-Capital Region',
        VOV: 'East Flanders',
        VBR: 'Flemish Brabant',
        VLG: 'Flemish Region',
        WHT: 'Hainaut',
        VLI: 'Limburg',
        WLG: 'Liège',
        WLX: 'Luxembourg',
        WNA: 'Namur',
        WBR: 'Walloon Brabant',
        WAL: 'Walloon Region',
        VWV: 'West Flanders',
    },
    BZ: {
        BZ: 'Belize District',
        CY: 'Cayo',
        CZL: 'Corozal',
        OW: 'Orange Walk',
        SC: 'Stann Creek',
        TOL: 'Toledo',
    },
    BJ: {
        AL: 'Alibori',
        AK: 'Atakora',
        AQ: 'Atlantique',
        BO: 'Borgou',
        CO: 'Collines',
        DO: 'Donga',
        KO: 'Kouffo',
        LI: 'Li̅ttoral',
        MO: 'Mono',
        OU: 'Ouémé',
        PL: 'Plateau',
        ZO: 'Zou',
    },
    BM: {
        DEV: 'Devonshire',
        HMT: 'Hamilton (City)',
        HAM: 'Hamilton Parish',
        PAG: 'Paget',
        PEM: 'Pembroke',
        SAI: 'Saint George’s',
        SAN: 'Sandys',
        SMI: 'Smith’s',
        SOU: 'Southampton',
        SGE: 'St. George’s (Town)',
        WAR: 'Warwick',
    },
    BT: {
        '34': 'Bumthang',
        '12': 'Chhukha',
        '22': 'Dagana',
        '24': 'Gasa',
        '13': 'Ha',
        '43': 'Lhuentse',
        '42': 'Monggar',
        '11': 'Paro',
        '45': 'Pemagatshel',
        '23': 'Punakha',
        '46': 'Samdrup Jongkha',
        '14': 'Samtse',
        '32': 'Sarpang',
        '15': 'Thimphu',
        '44': 'Trashi Yangtse',
        '41': 'Trashigang',
        '33': 'Trongsa',
        '21': 'Tsirang',
        '31': 'Wangdue Phodrang',
        '35': 'Zhemgang',
    },
    BO: {
        H: 'Chuquisaca',
        C: 'Cochabamba',
        B: 'El Beni',
        L: 'La Paz',
        O: 'Oruro',
        N: 'Pando',
        P: 'Potosí',
        S: 'Santa Cruz',
        T: 'Tarija',
    },
    BQ: {
        BO: 'Bonaire',
        SA: 'Saba',
        SE: 'Sint Eustatius',
    },
    BA: {
        '05': 'Bosnian-Podrinje Goražde',
        BRC: 'Brčko District',
        '10': 'Canton 10 (Hercegbosanski)',
        '06': 'Central Bosnia Canton',
        BIH: 'Federation of Bosnia and Herzegovina',
        '07': 'Herzegovina-Neretva Canton',
        '02': 'Posavina Canton',
        SRP: 'Republika Srpska',
        '09': 'Sarajevo Canton',
        '03': 'Tuzla Canton',
        '01': 'Una-Sana Canton',
        '08': 'West Herzegovina Canton',
        '04': 'Zenica-Doboj Canton',
    },
    BW: {
        CE: 'Central',
        GH: 'Ghanzi',
        KG: 'Kgalagadi',
        KL: 'Kgatleng',
        KW: 'Kweneng',
        NG: 'Ngamiland',
        NE: 'North-East',
        NW: 'North-West',
        SE: 'South-East',
        SO: 'Southern',
    },
    BV: {
        BI: 'Bouvet Island',
    },
    BR: {
        AC: 'Acre',
        AL: 'Alagoas',
        AP: 'Amapá',
        AM: 'Amazonas',
        BA: 'Bahia',
        CE: 'Ceará',
        DF: 'Distrito Federal',
        ES: 'Espírito Santo',
        GO: 'Goiás',
        MA: 'Maranhão',
        MT: 'Mato Grosso',
        MS: 'Mato Grosso do Sul',
        MG: 'Minas Gerais',
        PR: 'Paraná',
        PB: 'Paraíba',
        PA: 'Pará',
        PE: 'Pernambuco',
        PI: 'Piauí',
        RN: 'Rio Grande do Norte',
        RS: 'Rio Grande do Sul',
        RJ: 'Rio de Janeiro',
        RO: 'Rondônia',
        RR: 'Roraima',
        SC: 'Santa Catarina',
        SE: 'Sergipe',
        SP: 'São Paulo',
        TO: 'Tocantins',
    },
    IO: {
        BIOT: 'British Indian Ocean Territory',
    },
    BN: {
        BE: 'Belait',
        BM: 'Brunei-Muara',
        TE: 'Temburong',
        TU: 'Tutong',
    },
    BG: {
        '01': 'Blagoevgrad',
        '02': 'Burgas',
        '08': 'Dobrich',
        '07': 'Gabrovo',
        '26': 'Haskovo',
        '09': 'Kardzhali',
        '10': 'Kyustendil',
        '11': 'Lovech',
        '12': 'Montana',
        '13': 'Pazardzhik',
        '14': 'Pernik',
        '15': 'Pleven',
        '16': 'Plovdiv',
        '17': 'Razgrad',
        '18': 'Ruse',
        '27': 'Shumen',
        '19': 'Silistra',
        '20': 'Sliven',
        '21': 'Smolyan',
        '23': 'Sofia',
        '22': 'Sofia-Grad',
        '24': 'Stara Zagora',
        '25': 'Targovishte',
        '03': 'Varna',
        '04': 'Veliko Tarnovo',
        '05': 'Vidin',
        '06': 'Vratsa',
        '28': 'Yambol',
    },
    BF: {
        '01': 'Boucle du Mouhoun',
        '02': 'Cascades',
        '03': 'Centre',
        '04': 'Centre-Est',
        '05': 'Centre-Nord',
        '06': 'Centre-Ouest',
        '07': 'Centre-Sud',
        '08': 'Est',
        '09': 'Hauts-Bassins',
        '10': 'Nord',
        '11': 'Plateau-Central',
        '12': 'Sahel',
        '13': 'Sud-Ouest',
    },
    BI: {
        BB: 'Bubanza',
        BJ: 'Bujumbura',
        BM: 'Bujumbura Mairie',
        BL: 'Bujumbura Rural',
        BR: 'Bururi',
        CA: 'Cankuzo',
        CI: 'Cibitoke',
        GI: 'Gitega',
        KR: 'Karuzi',
        KY: 'Kayanza',
        KI: 'Kirundo',
        MA: 'Makamba',
        MU: 'Muramvya',
        MY: 'Muyinga',
        MW: 'Mwaro',
        NG: 'Ngozi',
        RM: 'Rumonge',
        RT: 'Rutana',
    },
    KH: {
        '1': 'Banteay Meanchey',
        '2': 'Battambang',
        '10': 'Kampong Cham',
        '3': 'Kampong Cham (deprecated old code)',
        '11': 'Kampong Chhnang',
        '12': 'Kampong Speu',
        '13': 'Kampong Thom',
        '14': 'Kampot',
        '15': 'Kandal',
        '30': 'Kep',
        '16': 'Koh Kong',
        '17': 'Kratie',
        '18': 'Mondulkiri',
        '29': 'Oddar Meanchey',
        '31': 'Pailin',
        '19': 'Phnom Penh',
        '25': 'Preah Sihanouk',
        '20': 'Preah Vihear',
        '21': 'Prey Veng',
        '22': 'Pursat',
        '23': 'Ratanakiri',
        '24': 'Siem Reap',
        '26': 'Stung Treng',
        '27': 'Svay Rieng',
        '28': 'Takéo',
        '32': 'Tbong Khmum',
    },
    CM: {
        AD: 'Adamaoua',
        CE: 'Centre',
        ES: 'East',
        EN: 'Far North',
        LT: 'Littoral',
        NO: 'North',
        NW: 'North-West',
        SU: 'South',
        SW: 'South-West',
        OU: 'West',
    },
    CA: {
        AB: 'Alberta',
        BC: 'British Columbia',
        MB: 'Manitoba',
        NB: 'New Brunswick',
        NL: 'Newfoundland and Labrador',
        NT: 'Northwest Territories',
        NS: 'Nova Scotia',
        NU: 'Nunavut',
        ON: 'Ontario',
        PE: 'Prince Edward Island',
        QC: 'Quebec',
        SK: 'Saskatchewan',
        YT: 'Yukon',
    },
    CV: {
        BV: 'Boa Vista',
        BR: 'Brava',
        CS: 'Calheta de São Miguel',
        MA: 'Maio',
        MO: 'Mosteiros',
        PA: 'Paul',
        PN: 'Porto Novo',
        PR: 'Praia',
        RB: 'Ribeira Brava',
        RG: 'Ribeira Grande',
        RS: 'Ribeira Grande de Santiago',
        SL: 'Sal',
        SM: 'Santa Catarina',
        SD: 'Santa Catarina do Fogo',
        SF: 'São Filipe',
        SO: 'São Lourenço dos Órgãos',
        SN: 'São Nicolau',
        SS: 'São Salvador do Mundo',
        SV: 'São Vicente',
        TA: 'Tarrafal',
        TZ: 'Tarrafal (deprecated code—use TS?)',
        TS: 'Tarrafal de São Nicolau',
    },
    KY: {
        CI: 'Cayman Islands',
    },
    CF: {
        BB: 'Bamingui-Bangoran',
        BKO: 'Bangoran (Economic Prefecture, older code BB?)',
        AC: 'Bangui (Autonomous Commune)',
        BK: 'Basse-Kotto',
        KB: 'Gribingui',
        HM: 'Haut-Mbomou',
        HK: 'Haute-Kotto',
        HS: 'Haute-Sangha / Mambéré-Kadéï',
        KG: 'Kémo',
        LB: 'Lobaye',
        MB: 'Mbomou',
        NM: 'Nana-Mambéré',
        MP: 'Ombella-M’Poko',
        UK: 'Ouaka',
        OP: 'Ouham-Pendé',
        SE: 'Sangha',
        VK: 'Vakaga',
    },
    TD: {
        BG: 'Bagirmi',
        BA: 'Batha',
        BO: 'Borkou',
        CB: 'Chari-Baguirmi',
        EN: 'Ennedi-Est',
        EO: 'Ennedi-Ouest',
        GR: 'Guéra',
        HL: 'Hadjer-Lamis',
        KA: 'Kanem',
        LC: 'Lac',
        LO: 'Logone-Occidental',
        LR: 'Logone-Oriental',
        MA: 'Mandoul',
        ME: 'Mayo-Kebbi-Est',
        MO: 'Mayo-Kebbi-Ouest',
        MEF: 'Moyen-Chari (sometimes MC)',
        ND: 'N’Djamena',
        OD: 'Ouaddaï',
        SA: 'Salamat',
        SI: 'Sila',
        TA: 'Tandjilé',
        TI: 'Tibesti',
        WF: 'Wadi Fira',
    },
    CL: {
        AI: 'Aisén del General Carlos Ibáñez del Campo',
        AN: 'Antofagasta',
        AP: 'Arica y Parinacota',
        AT: 'Atacama',
        BI: 'Biobío',
        CO: 'Coquimbo',
        AR: 'La Araucanía',
        LI: 'Libertador General Bernardo O’Higgins',
        LL: 'Los Lagos',
        LR: 'Los Ríos',
        MA: 'Magallanes',
        ML: 'Maule',
        RM: 'Región Metropolitana de Santiago',
        TA: 'Tarapacá',
        VS: 'Valparaíso',
        NB: 'Ñuble',
    },
    CN: {
        AH: 'Anhui',
        BJ: 'Beijing',
        CQ: 'Chongqing',
        FJ: 'Fujian',
        GS: 'Gansu',
        GD: 'Guangdong',
        GX: 'Guangxi Zhuang',
        GZ: 'Guizhou',
        HAI: 'Hainan',
        HE: 'Hebei',
        HL: 'Heilongjiang',
        HA: 'Henan',
        HK: 'Hong Kong',
        HB: 'Hubei',
        HN: 'Hunan',
        NM: 'Inner Mongolia',
        JS: 'Jiangsu',
        JX: 'Jiangxi',
        JL: 'Jilin',
        LN: 'Liaoning',
        MO: 'Macao',
        NX: 'Ningxia Hui',
        QH: 'Qinghai',
        SN: 'Shaanxi',
        SD: 'Shandong',
        SH: 'Shanghai',
        SX: 'Shanxi',
        SC: 'Sichuan',
        TW: 'Taiwan',
        TJ: 'Tianjin',
        XZ: 'Tibet (Xizang)',
        XJ: 'Xinjiang Uyghur',
        YN: 'Yunnan',
        ZJ: 'Zhejiang',
    },
    CX: {
        CI: 'Christmas Island',
    },
    CC: {
        CI: 'Cocos (Keeling) Islands',
    },
    CO: {
        AMA: 'Amazonas',
        ANT: 'Antioquia',
        ARA: 'Arauca',
        ATL: 'Atlántico',
        BOL: 'Bolívar',
        BOY: 'Boyacá',
        CAL: 'Caldas',
        CAQ: 'Caquetá',
        CAS: 'Casanare',
        CAU: 'Cauca',
        CES: 'Cesar',
        CHO: 'Chocó',
        CUN: 'Cundinamarca',
        COR: 'Córdoba',
        DC: 'Distrito Capital de Bogotá',
        GUA: 'Guainía',
        GUV: 'Guaviare',
        HUI: 'Huila',
        LAG: 'La Guajira',
        MAG: 'Magdalena',
        MET: 'Meta',
        NAR: 'Nariño',
        NSA: 'Norte de Santander',
        PAT: 'Putumayo',
        QUI: 'Quindío',
        RIS: 'Risaralda',
        SAP: 'San Andrés, Providencia y Santa Catalina',
        SAN: 'Santander',
        SUC: 'Sucre',
        TOL: 'Tolima',
        VAC: 'Valle del Cauca',
        VAU: 'Vaupés',
        VID: 'Vichada',
    },
    KM: {
        A: 'Anjouan (Ndzuwani)',
        G: 'Grande Comore (Njazidja)',
        M: 'Mohéli (Mwali)',
    },
    CG: {
        '11': 'Bouenza',
        '12': 'Brazzaville',
        '13': 'Cuvette',
        '14': 'Cuvette-Ouest',
        '15': 'Kouilou',
        '2': 'Likouala',
        '16': 'Lékoumou',
        CU: 'Ngöbe? (Some older references may differ)',
        '9': 'Niari',
        '5': 'Plateaux',
        '7': 'Pool',
        '8': 'Sangha',
    },
    CD: {
        BU: 'Bas-Uélé',
        HK: 'Haut-Katanga',
        HL: 'Haut-Lomami',
        HU: 'Haut-Uélé',
        IT: 'Ituri',
        KD: 'Kasai',
        KC: 'Kasai Central',
        KE: 'Kasai Oriental',
        KN: 'Kinshasa',
        BC: 'Kongo Central (Bas-Congo)',
        KS: 'Kwango',
        KW: 'Kwilu',
        LO: 'Lomami',
        LU: 'Lualaba',
        MN: 'Mai-Ndombe',
        MA: 'Maniema',
        MO: 'Mongala',
        NK: 'Nord-Kivu',
        NU: 'Nord-Ubangi',
        SA: 'Sankuru',
        SK: 'Sud-Kivu',
        SU: 'Sud-Ubangi',
        TA: 'Tanganyika',
        TU: 'Tshopo',
        TU2: 'Tshuapa',
        EQ: 'Équateur',
    },
    CK: {
        CI: 'Cook Islands',
    },
    CR: {
        A: 'Alajuela',
        C: 'Cartago',
        G: 'Guanacaste',
        H: 'Heredia',
        L: 'Limón',
        P: 'Puntarenas',
        SJ: 'San José',
    },
    CI: {
        AB: 'Abidjan (Autonomous District)',
        BS: 'Bas-Sassandra',
        CM: 'Comoé',
        DN: 'Denguélé',
        GD: 'Gôh-Djiboua',
        LC: 'Lacs',
        LG: 'Lagunes',
        MG: 'Montagnes',
        SM: 'Sassandra-Marahoué',
        SV: 'Savanes',
        VB: 'Vallée du Bandama',
        WR: 'Woroba',
        YM: 'Yamoussoukro (Autonomous District)',
        ZZ: 'Zanzan',
    },
    HR: {
        '07': 'Bjelovarsko-bilogorska',
        '12': 'Brodsko-posavska',
        '19': 'Dubrovačko-neretvanska',
        '21': 'Grad Zagreb',
        '18': 'Istarska',
        '04': 'Karlovačka',
        '06': 'Koprivničko-križevačka',
        '02': 'Krapinsko-zagorska',
        '09': 'Ličko-senjska',
        '20': 'Međimurska',
        '14': 'Osječko-baranjska',
        '11': 'Požeško-slavonska',
        '08': 'Primorsko-goranska',
        '03': 'Sisačko-moslavačka',
        '17': 'Splitsko-dalmatinska',
        '05': 'Varaždinska',
        '10': 'Virovitičko-podravska',
        '16': 'Vukovarsko-srijemska',
        '13': 'Zadarska',
        '01': 'Zagrebačka',
        '15': 'Šibensko-kninska',
    },
    CW: {
        CR: 'Curaçao',
    },
    CY: {
        '01': 'Famagusta (Ammóchostos)',
        '02': 'Kyrenia (Kýrenia)',
        '03': 'Larnaca (Lárnaka)',
        '05': 'Limassol (Lemesós)',
        '04': 'Nicosia (Lefkosía)',
        '06': 'Paphos (Páfos)',
    },
    CZ: {
        JM: 'Jihomoravský',
        JC: 'Jihočeský',
        KA: 'Karlovarský',
        HK: 'Královéhradecký',
        LB: 'Liberecký',
        MO: 'Moravskoslezský',
        OL: 'Olomoucký',
        PA: 'Pardubický',
        PL: 'Plzeňský',
        PR: 'Praha (Prague)',
        ST: 'Středočeský',
        VY: 'Vysočina',
        ZL: 'Zlínský',
        US: 'Ústecký',
    },
    DK: {
        '84': 'Hovedstaden',
        '82': 'Midtjylland',
        '81': 'Nordjylland',
        '85': 'Sjælland',
        '83': 'Syddanmark',
    },
    DJ: {
        AS: 'Ali Sabieh',
        AR: 'Arta',
        DI: 'Dikhil',
        DK: 'Dikhil',
        DJ: 'Djibouti City',
        OB: 'Obock',
        TA: 'Tadjourah',
    },
    DM: {
        '02': 'Saint Andrew',
        '03': 'Saint David',
        '04': 'Saint George',
        '05': 'Saint John',
        '06': 'Saint Joseph',
        '07': 'Saint Luke',
        '08': 'Saint Mark',
        '09': 'Saint Patrick',
        '10': 'Saint Paul',
        '01': 'Saint Peter',
    },
    DO: {
        '02': 'Azua',
        '03': 'Baoruco',
        '04': 'Barahona',
        '05': 'Dajabón',
        '01': 'Distrito Nacional (Santo Domingo)',
        '06': 'Duarte',
        '08': 'El Seibo',
        '07': 'Elías Piña',
        '09': 'Espaillat',
        '30': 'Hato Mayor',
        '10': 'Independencia',
        '11': 'La Altagracia',
        '12': 'La Romana',
        '13': 'La Vega',
        '14': 'María Trinidad Sánchez',
        '28': 'Monseñor Nouel',
        '15': 'Monte Cristi',
        '29': 'Monte Plata',
        '16': 'Pedernales',
        '17': 'Peravia',
        '18': 'Puerto Plata',
        '19': 'Salcedo (Hermanas Mirabal)',
        '20': 'Samaná',
        '21': 'San Cristóbal',
        '31': 'San José de Ocoa',
        '22': 'San Juan',
        '23': 'San Pedro de Macorís',
        '25': 'Santiago',
        '26': 'Santiago Rodríguez',
        '32': 'Santo Domingo',
        '24': 'Sánchez Ramírez',
        '27': 'Valverde',
    },
    EC: {
        A: 'Azuay',
        B: 'Bolívar',
        C: 'Carchi',
        F: 'Cañar',
        H: 'Chimborazo',
        X: 'Cotopaxi',
        O: 'El Oro',
        E: 'Esmeraldas',
        W: 'Galápagos',
        G: 'Guayas',
        I: 'Imbabura',
        L: 'Loja',
        R: 'Los Ríos',
        M: 'Manabí',
        S: 'Morona-Santiago',
        N: 'Napo',
        D: 'Orellana',
        Y: 'Pastaza',
        P: 'Pichincha',
        SE: 'Santa Elena',
        SD: 'Santo Domingo de los Tsáchilas',
        U: 'Sucumbíos',
        T: 'Tungurahua',
        Z: 'Zamora-Chinchipe',
    },
    EG: {
        SHR: 'Al Sharqia (Ash Sharqiyah)',
        ALX: 'Alexandria',
        ASN: 'Aswan',
        AST: 'Asyut',
        BA: 'Beheira',
        BNS: 'Beni Suef',
        C: 'Cairo',
        DK: 'Dakahlia',
        DT: 'Damietta',
        FYM: 'Faiyum',
        GH: 'Gharbia',
        GZ: 'Giza',
        IS: 'Ismailia',
        KFS: 'Kafr El Sheikh',
        LX: 'Luxor (Al Uqsur)',
        MT: 'Matrouh (Marsa Matruh)',
        MN: 'Minya (Al Minya)',
        MNF: 'Monufia (Al Minufiyah)',
        WAD: 'New Valley (Al Wadi al Jadid)',
        SIN: 'North Sinai (Shamal Sina)',
        PTS: 'Port Said',
        KB: 'Qalyubia (Al Qalyubiyah)',
        KN: 'Qena',
        BAH: 'Red Sea (Al Bahr al Ahmar)',
        SHG: 'Sohag',
        JS: 'South Sinai (Janub Sina)',
        SUZ: 'Suez',
    },
    SV: {
        AH: 'Ahuachapán',
        CA: 'Cabañas',
        CH: 'Chalatenango',
        CU: 'Cuscatlán',
        LI: 'La Libertad',
        PA: 'La Paz',
        UN: 'La Unión',
        MO: 'Morazán',
        SM: 'San Miguel',
        SS: 'San Salvador',
        SV: 'San Vicente',
        SA: 'Santa Ana',
        SO: 'Sonsonate',
        US: 'Usulután',
    },
    GQ: {
        AN: 'Annobón',
        BN: 'Bioko Norte',
        BS: 'Bioko Sur',
        CS: 'Centro Sur',
        DJ: 'Djibloho (new province created in 2017)',
        KN: 'Kie-Ntem',
        LI: 'Litoral',
        WN: 'Wele-Nzas',
    },
    ER: {
        DU: 'Al Janūbī (Debub)',
        AN: 'Anelba (Anseba)',
        GB: 'Gash-Barka',
        DK: 'Janūbī al Baḥrī al Aḥmar (Southern Red Sea)',
        MA: 'Ma’ākel (Central)',
        SK: 'Shimālī al Baḥrī al Aḥmar (Northern Red Sea)',
    },
    EE: {
        '37': 'Harju',
        '39': 'Hiiu',
        '44': 'Ida-Viru',
        '51': 'Järva',
        '49': 'Jõgeva',
        '57': 'Lääne',
        '59': 'Lääne-Viru',
        '67': 'Pärnu',
        '65': 'Põlva',
        '70': 'Rapla',
        '74': 'Saare',
        '78': 'Tartu',
        '82': 'Valga',
        '84': 'Viljandi',
        '86': 'Võru',
    },
    SZ: {
        HH: 'Hhohho',
        LU: 'Lubombo',
        MA: 'Manzini',
        SH: 'Shiselweni',
    },
    ET: {
        AA: 'Addis Ababa',
        AF: 'Afar',
        AM: 'Amhara',
        BE: 'Benishangul-Gumuz',
        DD: 'Dire Dawa',
        GA: 'Gambela',
        HA: 'Harari',
        OR: 'Oromia',
        SI: 'Sidama',
        SM: 'Somali',
        SN: 'Southern Nations, Nationalities, and Peoples’',
        TI: 'Tigray',
    },
    FK: {
        FI: 'Falkland Islands (Islas Malvinas)',
    },
    FO: {
        FI: 'Faroe Islands',
    },
    FJ: {
        C: 'Central',
        E: 'Eastern',
        N: 'Northern',
        R: 'Rotuma',
        W: 'Western',
    },
    FI: {
        '08': 'Central Finland',
        '07': 'Central Ostrobothnia',
        '05': 'Kainuu',
        '09': 'Kymenlaakso',
        '10': 'Lapland',
        '13': 'North Karelia',
        '14': 'Northern Ostrobothnia',
        '15': 'Northern Savonia',
        '12': 'Ostrobothnia',
        '11': 'Pirkanmaa',
        '16': 'Päijät-Häme',
        '17': 'Satakunta',
        '02': 'South Karelia',
        '03': 'Southern Ostrobothnia',
        '04': 'Southern Savonia',
        '19': 'Southwest Finland (Varsinais-Suomi)',
        '06': 'Tavastia Proper (Kanta-Häme)',
        '18': 'Uusimaa',
        '01': 'Åland',
    },
    FR: {
        ARA: 'Auvergne-Rhône-Alpes',
        BFC: 'Bourgogne-Franche-Comté',
        BRE: 'Bretagne',
        CVL: 'Centre-Val de Loire',
        COR: 'Corse',
        GES: 'Grand Est',
        GP: 'Guadeloupe',
        GF: 'Guyane (French Guiana)',
        HDF: 'Hauts-de-France',
        RE: 'La Réunion',
        MQ: 'Martinique',
        YT: 'Mayotte',
        NOR: 'Normandie',
        NAQ: 'Nouvelle-Aquitaine',
        OCC: 'Occitanie',
        PDL: 'Pays de la Loire',
        PAC: 'Provence-Alpes-Côte d’Azur',
        IDF: 'Île-de-France',
    },
    GF: {
        FG: 'French Guiana',
    },
    PF: {
        FP: 'French Polynesia',
    },
    TF: {
        FST: 'French Southern Territories',
    },
    GA: {
        '1': 'Estuaire',
        '2': 'Haut-Ogooué',
        '3': 'Moyen-Ogooué',
        '4': 'Ngounié',
        '5': 'Nyanga',
        '6': 'Ogooué-Ivindo',
        '7': 'Ogooué-Lolo',
        '8': 'Ogooué-Maritime',
        '9': 'Woleu-Ntem',
    },
    GM: {
        B: 'Banjul',
        M: 'Central River',
        L: 'Lower River',
        N: 'North Bank',
        U: 'Upper River',
        W: 'West Coast',
    },
    GE: {
        AB: 'Abkhazia (disputed)',
        AJ: 'Adjara (Adzharia)',
        GU: 'Guria',
        IM: 'Imereti',
        KA: 'Kakheti',
        KK: 'Kvemo Kartli',
        MM: 'Mtskheta-Mtianeti',
        RL: 'Racha-Lechkhumi and Kvemo Svaneti',
        SZ: 'Samegrelo-Zemo Svaneti',
        SJ: 'Samtskhe-Javakheti',
        TB: 'Tbilisi (capital city)',
    },
    DE: {
        BW: 'Baden-Württemberg',
        BY: 'Bayern (Bavaria)',
        BE: 'Berlin',
        BB: 'Brandenburg',
        HB: 'Bremen',
        HH: 'Hamburg',
        HE: 'Hessen (Hesse)',
        MV: 'Mecklenburg-Vorpommern',
        NI: 'Niedersachsen (Lower Saxony)',
        NW: 'Nordrhein-Westfalen',
        RP: 'Rheinland-Pfalz (Rhineland-Palatinate)',
        SL: 'Saarland',
        SN: 'Sachsen (Saxony)',
        ST: 'Sachsen-Anhalt',
        SH: 'Schleswig-Holstein',
        TH: 'Thüringen (Thuringia)',
    },
    GH: {
        AF: 'Ahafo',
        AH: 'Ashanti',
        BO: 'Bono',
        BE: 'Bono East',
        BA: 'Brong-Ahafo',
        CP: 'Central',
        EP: 'Eastern',
        AA: 'Greater Accra',
        NE: 'North East',
        NP: 'Northern',
        OT: 'Oti',
        SV: 'Savannah',
        UE: 'Upper East',
        UW: 'Upper West',
        TV: 'Volta',
        WP: 'Western',
        WN: 'Western North',
    },
    GI: {
        G: 'Gibraltar',
    },
    GR: {
        A: 'Anatolikí Makedonía kai Thráki',
        I: 'Attikí',
        G: 'Dytikí Elláda',
        C: 'Dytikí Makedonía',
        F: 'Ionía Nísia',
        B: 'Kentrikí Makedonía',
        M: 'Kríti (Crete)',
        L: 'Notío Aigaío (South Aegean)',
        J: 'Peloponnísos',
        H: 'Stérea Elláda (Central Greece)',
        E: 'Thessalía',
        K: 'Voreío Aigaío (North Aegean)',
        '69': 'Ágion Óros (Mount Athos)',
        D: 'Ípeiros',
    },
    GL: {
        G: 'Greenland',
    },
    GD: {
        '10': 'Carriacou and Petite Martinique',
        '01': 'Saint Andrew',
        '02': 'Saint David',
        '03': 'Saint George',
        '04': 'Saint John',
        '05': 'Saint Mark',
        '06': 'Saint Patrick',
    },
    GP: {
        G: 'Guadeloupe',
    },
    GU: {
        G: 'Guam',
    },
    GT: {
        AV: 'Alta Verapaz',
        BV: 'Baja Verapaz',
        CM: 'Chimaltenango',
        CQ: 'Chiquimula',
        PR: 'El Progreso',
        ES: 'Escuintla',
        GU: 'Guatemala',
        HU: 'Huehuetenango',
        IZ: 'Izabal',
        JA: 'Jalapa',
        JU: 'Jutiapa',
        PE: 'Petén',
        QZ: 'Quetzaltenango',
        QC: 'Quiché',
        RE: 'Retalhuleu',
        SA: 'Sacatepéquez',
        SM: 'San Marcos',
        SR: 'Santa Rosa',
        SO: 'Sololá',
        SU: 'Suchitepéquez',
        TO: 'Totonicapán',
        ZA: 'Zacapa',
    },
    GG: {
        G: 'Guernsey',
    },
    GN: {
        B: 'Boké',
        C: 'Conakry (special zone)',
        F: 'Faranah',
        K: 'Kankan',
        D: 'Kindia',
        L: 'Labé',
        M: 'Mamou',
        N: 'Nzérékoré',
    },
    GW: {
        BA: 'Bafatá',
        BM: 'Biombo',
        BS: 'Bissau (autonomous)',
        BL: 'Bolama/Bijagos',
        CA: 'Cacheu',
        GA: 'Gabú',
        OI: 'Oio',
        QU: 'Quinara',
        TO: 'Tombali',
    },
    GY: {
        BA: 'Barima-Waini',
        CU: 'Cuyuni-Mazaruni',
        DE: 'Demerara-Mahaica',
        EB: 'East Berbice-Corentyne',
        ES: 'Essequibo Islands-West Demerara',
        MA: 'Mahaica-Berbice',
        PM: 'Pomeroon-Supenaam',
        PT: 'Potaro-Siparuni',
        UD: 'Upper Demerara-Berbice',
        UT: 'Upper Takutu-Upper Essequibo',
    },
    HT: {
        AR: 'Artibonite',
        CE: 'Centre',
        GA: 'Grande’Anse',
        NI: 'Nippes',
        ND: 'Nord',
        NE: 'Nord-Est',
        NO: 'Nord-Ouest',
        OU: 'Ouest',
        SD: 'Sud',
        SE: 'Sud-Est',
    },
    HM: {
        HI: 'Heard Island and McDonald Islands',
    },
    VA: {
        VC: 'Vatican City',
    },
    HN: {
        AT: 'Atlántida',
        CH: 'Choluteca',
        CL: 'Colón',
        CM: 'Comayagua',
        CP: 'Copán',
        CR: 'Cortés',
        EP: 'El Paraíso',
        FM: 'Francisco Morazán',
        GD: 'Gracias a Dios',
        IN: 'Intibucá',
        IB: 'Islas de la Bahía (Bay Islands)',
        LP: 'La Paz',
        LE: 'Lempira',
        OC: 'Ocotepeque',
        OL: 'Olancho',
        SB: 'Santa Bárbara',
        VA: 'Valle',
        YO: 'Yoro',
    },
    HK: {
        HK: 'Hong Kong SAR',
    },
    HU: {
        BA: 'Baranya',
        BZ: 'Borsod-Abaúj-Zemplén',
        BU: 'Budapest (capital city)',
        BK: 'Bács-Kiskun',
        BE: 'Békés',
        BC: 'Békéscsaba (City with county rights)',
        CS: 'Csongrád-Csanád',
        DE: 'Debrecen (City)',
        DU: 'Dunaújváros (City)',
        EG: 'Eger (City)',
        FE: 'Fejér',
        GY: 'Győr (City)',
        GS: 'Győr-Moson-Sopron',
        HB: 'Hajdú-Bihar',
        HE: 'Heves',
        HV: 'Hódmezővásárhely (City)',
        JN: 'Jász-Nagykun-Szolnok',
        KV: 'Kaposvár (City)',
        KM: 'Kecskemét (City)',
        KE: 'Komárom-Esztergom',
        MI: 'Miskolc (City)',
        NK: 'Nagykanizsa (City)',
        NY: 'Nyíregyháza (City)',
        NO: 'Nógrád',
        PE: 'Pest',
        PS: 'Pécs (City)',
        SO: 'Somogy',
        SN: 'Sopron (City)',
        SZ: 'Szabolcs-Szatmár-Bereg',
        SD: 'Szeged (City)',
        SK: 'Szolnok (City)',
        SS: 'Szombathely (City)',
        SH: 'Székesfehérvár (City)',
        TB: 'Tatabánya (City)',
        TO: 'Tolna',
        VA: 'Vas',
        VE: 'Veszprém',
        VM: 'Veszprém (City)',
        ZA: 'Zala',
        ZE: 'Zalaegerszeg (City)',
        ER: 'Érd (City)',
    },
    IS: {
        '7': 'Austurland',
        '1': 'Höfuðborgarsvæði (Capital Region)',
        '6': 'Norðurland eystra',
        '5': 'Norðurland vestra',
        '8': 'Suðurland',
        '2': 'Suðurnes',
        '4': 'Vestfirðir',
        '3': 'Vesturland',
    },
    IN: {
        AN: 'Andaman and Nicobar Islands',
        AP: 'Andhra Pradesh',
        AR: 'Arunachal Pradesh',
        AS: 'Assam',
        BR: 'Bihar',
        CH: 'Chandigarh',
        CT: 'Chhattisgarh',
        DH: 'Dadra & Nagar Haveli and Daman & Diu',
        DL: 'Delhi (National Capital Territory)',
        GA: 'Goa',
        GJ: 'Gujarat',
        HR: 'Haryana',
        HP: 'Himachal Pradesh',
        JK: 'Jammu and Kashmir',
        JH: 'Jharkhand',
        KA: 'Karnataka',
        KL: 'Kerala',
        LA: 'Ladakh',
        LD: 'Lakshadweep',
        MP: 'Madhya Pradesh',
        MH: 'Maharashtra',
        MN: 'Manipur',
        ML: 'Meghalaya',
        MZ: 'Mizoram',
        NL: 'Nagaland',
        OR: 'Odisha (Orissa)',
        PY: 'Puducherry (Pondicherry)',
        PB: 'Punjab',
        RJ: 'Rajasthan',
        SK: 'Sikkim',
        TN: 'Tamil Nadu',
        TG: 'Telangana',
        TR: 'Tripura',
        UP: 'Uttar Pradesh',
        UT: 'Uttarakhand',
        WB: 'West Bengal',
    },
    ID: {
        AC: 'Aceh',
        BA: 'Bali',
        BT: 'Banten',
        BE: 'Bengkulu',
        GO: 'Gorontalo',
        JK: 'Jakarta (Daerah Khusus Ibukota)',
        JA: 'Jambi',
        JB: 'Jawa Barat',
        JT: 'Jawa Tengah',
        JI: 'Jawa Timur',
        KB: 'Kalimantan Barat',
        KS: 'Kalimantan Selatan',
        KT: 'Kalimantan Tengah',
        KI: 'Kalimantan Timur',
        KA: 'Kalimantan Utara',
        BB: 'Kepulauan Bangka Belitung',
        KR: 'Kepulauan Riau',
        LA: 'Lampung',
        MA: 'Maluku',
        MU: 'Maluku Utara',
        NB: 'Nusa Tenggara Barat',
        NT: 'Nusa Tenggara Timur',
        PA: 'Papua',
        PB: 'Papua Barat',
        PT: 'Papua Pegunungan (new province, 2022*)',
        PS: 'Papua Selatan (new province, 2022*)',
        PM: 'Papua Tengah (new province, 2022*)',
        RI: 'Riau',
        PL: 'Sulawesi Barat',
        SN: 'Sulawesi Selatan',
        ST: 'Sulawesi Tengah',
        SR: 'Sulawesi Tenggara',
        SA: 'Sulawesi Utara',
        SB: 'Sumatera Barat',
        SS: 'Sumatera Selatan',
        SU: 'Sumatera Utara',
        YO: 'Yogyakarta (Daerah Istimewa Yogyakarta)',
    },
    IQ: {
        AN: 'Al Anbar',
        BA: 'Al Basrah',
        MU: 'Al Muthanná',
        QA: 'Al Qādisiyyah',
        NA: 'An Najaf',
        AR: 'Arbīl (Erbil)',
        SU: 'As Sulaymānīyah (Sulaimani)',
        TH: 'At Taʼmīm (older code for Kirkuk)',
        BG: 'Baghdād (Baghdad)',
        BB: 'Bābil (Babil)',
        DA: 'Dahūk (Dohuk)',
        DQ: 'Dhī Qār (Dhi Qar)',
        DI: 'Diyālá (Diyala)',
        KA: 'Karbalā’ (Karbala)',
        KI: 'Kirkūk (Kirkuk)',
        MA: 'Maysān (Maysan)',
        NI: 'Nīnawá (Nineveh)',
        WA: 'Wāsiţ (Wasit)',
        SD: 'Şalāḩ ad Dīn (Salah al-Din)',
    },
    IE: {
        CW: 'Carlow',
        CN: 'Cavan',
        CE: 'Clare',
        CO: 'Cork',
        DL: 'Donegal',
        D: 'Dublin',
        G: 'Galway',
        KY: 'Kerry',
        KE: 'Kildare',
        KK: 'Kilkenny',
        LS: 'Laois',
        LM: 'Leitrim',
        LK: 'Limerick',
        LD: 'Longford',
        LH: 'Louth',
        MO: 'Mayo',
        MH: 'Meath',
        MN: 'Monaghan',
        OY: 'Offaly',
        RN: 'Roscommon',
        SO: 'Sligo',
        TA: 'Tipperary',
        WD: 'Waterford',
        WH: 'Westmeath',
        WX: 'Wexford',
        WW: 'Wicklow',
    },
    IM: {
        IM: 'Isle of Man',
    },
    IL: {
        D: 'HaDarom (Southern)',
        M: 'HaMerkaz (Central)',
        Z: 'HaZafon (Northern)',
        HA: 'Haifa',
        WB: 'Judea and Samaria (West Bank)',
        TA: 'Tel-Aviv',
        JM: 'Yerushalayim (Jerusalem)',
    },
    IT: {
        '65': 'Abruzzo',
        '77': 'Basilicata',
        '78': 'Calabria',
        '72': 'Campania',
        '45': 'Emilia-Romagna',
        '36': 'Friuli-Venezia Giulia',
        '62': 'Lazio',
        '42': 'Liguria',
        '25': 'Lombardia',
        '57': 'Marche',
        '67': 'Molise',
        '21': 'Piemonte',
        '75': 'Puglia',
        '88': 'Sardegna',
        '82': 'Sicilia',
        '52': 'Toscana',
        '32': 'Trentino-Alto Adige',
        '55': 'Umbria',
        '23': 'Valle d’Aosta',
        '34': 'Veneto',
    },
    JM: {
        '13': 'Clarendon',
        '09': 'Hanover',
        '01': 'Kingston',
        '12': 'Manchester',
        '04': 'Portland',
        '02': 'Saint Andrew',
        '06': 'Saint Ann',
        '14': 'Saint Catherine',
        '11': 'Saint Elizabeth',
        '08': 'Saint James',
        '05': 'Saint Mary',
        '03': 'Saint Thomas',
        '07': 'Trelawny',
        '10': 'Westmoreland',
    },
    JP: {
        '23': 'Aichi',
        '05': 'Akita',
        '02': 'Aomori',
        '12': 'Chiba',
        '38': 'Ehime',
        '18': 'Fukui',
        '40': 'Fukuoka',
        '07': 'Fukushima',
        '21': 'Gifu',
        '10': 'Gunma',
        '34': 'Hiroshima',
        '01': 'Hokkaidō',
        '28': 'Hyōgo',
        '08': 'Ibaraki',
        '17': 'Ishikawa',
        '03': 'Iwate',
        '37': 'Kagawa',
        '46': 'Kagoshima',
        '14': 'Kanagawa',
        '43': 'Kumamoto',
        '26': 'Kyōto',
        '39': 'Kōchi',
        '24': 'Mie',
        '04': 'Miyagi',
        '45': 'Miyazaki',
        '20': 'Nagano',
        '42': 'Nagasaki',
        '29': 'Nara',
        '15': 'Niigata',
        '33': 'Okayama',
        '47': 'Okinawa',
        '41': 'Saga',
        '11': 'Saitama',
        '25': 'Shiga',
        '32': 'Shimane',
        '22': 'Shizuoka',
        '09': 'Tochigi',
        '36': 'Tokushima',
        '31': 'Tottori',
        '16': 'Toyama',
        '13': 'Tōkyō',
        '30': 'Wakayama',
        '06': 'Yamagata',
        '35': 'Yamaguchi',
        '19': 'Yamanashi',
        '44': 'Ōita',
        '27': 'Ōsaka',
    },
    JE: {
        J: 'Jersey',
    },
    JO: {
        BA: 'Al Balqā’',
        KA: 'Al Karak',
        MA: 'Al Mafraq',
        AQ: 'Al ‘Aqaba (older variation of code AM)',
        AM: 'Al ‘Aqabah',
        AQ2: 'Aqaba (possible legacy code usage)',
        AZ: 'Az Zarqā’',
        TA: 'Aţ Ţafīlah',
        IR: 'Irbid',
        JA: 'Jarash',
        MN: 'Ma‘ān',
        MD: 'Mādabā',
        AJ: '‘Ajlūn',
    },
    KZ: {
        AKM: 'Akmola',
        AKT: 'Aktobe',
        ALA: 'Almaty (city)',
        ALM: 'Almaty (region)',
        AST: 'Astana (city, formerly Nur-Sultan)',
        ATY: 'Atyrau',
        BAY: 'Baykonyr (city within Kyzylorda?)**',
        VOS: 'East Kazakhstan',
        KAR: 'Karaganda',
        KZY: 'Kyzylorda',
        MAN: 'Mangystau',
        SEV: 'North Kazakhstan',
        PAV: 'Pavlodar',
        SHM: 'Shymkent (city)',
        YUZ: 'Turkistan (new region formerly South Kazakhstan)',
        KUS: 'Ulytau (new region from Karaganda, 2022)*',
        ZAP: 'West Kazakhstan',
        ZHA: 'Zhambyl',
        AMT: 'Zhetysu (new region from Almaty region, 2022)*',
    },
    KE: {
        '01': 'Baringo',
        '02': 'Bomet',
        '03': 'Bungoma',
        '04': 'Busia',
        '05': 'Elgeyo/Marakwet',
        '06': 'Embu',
        '07': 'Garissa',
        '08': 'Homa Bay',
        '09': 'Isiolo',
        '10': 'Kajiado',
        '11': 'Kakamega',
        '12': 'Kericho',
        '13': 'Kiambu',
        '14': 'Kilifi',
        '15': 'Kirinyaga',
        '16': 'Kisii',
        '17': 'Kisumu',
        '18': 'Kitui',
        '19': 'Kwale',
        '20': 'Laikipia',
        '21': 'Lamu',
        '22': 'Machakos',
        '23': 'Makueni',
        '24': 'Mandera',
        '25': 'Marsabit',
        '26': 'Meru',
        '27': 'Migori',
        '28': 'Mombasa',
        '29': 'Murang’a',
        '30': 'Nairobi City',
        '31': 'Nakuru',
        '32': 'Nandi',
        '33': 'Narok',
        '34': 'Nyamira',
        '35': 'Nyandarua',
        '36': 'Nyeri',
        '37': 'Samburu',
        '38': 'Siaya',
        '39': 'Taita–Taveta',
        '40': 'Tana River',
        '41': 'Tharaka-Nithi',
        '42': 'Trans Nzoia',
        '43': 'Turkana',
        '44': 'Uasin Gishu',
        '45': 'Vihiga',
        '46': 'Wajir',
        '47': 'West Pokot',
    },
    KI: {
        K: 'Kiribati',
    },
    KR: {
        '26': 'Busan (Gwangyeoksi)',
        '43': 'Chungcheongbuk-do',
        '44': 'Chungcheongnam-do',
        '27': 'Daegu (Gwangyeoksi)',
        '30': 'Daejeon (Gwangyeoksi)',
        '42': 'Gangwon-do',
        '29': 'Gwangju (Gwangyeoksi)',
        '41': 'Gyeonggi-do',
        '47': 'Gyeongsangbuk-do',
        '48': 'Gyeongsangnam-do',
        '28': 'Incheon (Gwangyeoksi)',
        '49': 'Jeju (Jeju Special Self-Governing Province)',
        '45': 'Jeollabuk-do',
        '46': 'Jeollanam-do',
        '36': 'Sejong (Teukbyeol Jachisi)',
        '11': 'Seoul (Teukbyeolsi)',
        '31': 'Ulsan (Gwangyeoksi)',
    },
    KW: {
        AH: 'Al Aḩmadī',
        FA: 'Al Farwānīyah',
        JA: 'Al Jahrrā’',
        KU: 'Al Kuwayt (Capital)',
        MU: 'Mubārak al Kabīr',
        HA: 'Ḩawallī',
    },
    KG: {
        B: 'Batken',
        GB: 'Bishkek (city)',
        C: 'Chüy',
        Y: 'Issyk-Kul (Ysyk-Köl)',
        J: 'Jalal-Abad',
        N: 'Naryn',
        GO: 'Osh (city)',
        O: 'Osh (region)',
        T: 'Talas',
    },
    LA: {
        AT: 'Attapu',
        BK: 'Bokèo',
        BL: 'Bolikhamxai',
        CH: 'Champasak',
        HO: 'Houaphan',
        KH: 'Khammouan',
        LM: 'Louang Namtha',
        LP: 'Louangphabang',
        OU: 'Oudômxai',
        PH: 'Phôngsali',
        SL: 'Salavan',
        SV: 'Savannakhét',
        VI: 'Vientiane (prefecture)',
        VT: 'Vientiane (province)',
        XA: 'Xaignabouri (Sainyabuli)',
        XS: 'Xaisomboun',
        XI: 'Xiangkhouang',
        XE: 'Xékong',
    },
    LV: {
        '004': 'Kurzeme',
        '006': 'Latgale',
        '002': 'Pierīga',
        '001': 'Rīga (City)',
        '003': 'Vidzeme',
        '005': 'Zemgale',
    },
    LB: {
        AK: 'Akkar',
        BH: 'Baalbek-Hermel',
        BA: 'Beirut (Bayrūt)',
        BI: 'Beqaa (Al Biqa‘)',
        JL: 'Mount Lebanon (Jabal Lubnān)',
        NA: 'Nabatieh (An Nabatiyah)',
        AS: 'North (Ash Shamal)',
        JA: 'South (Al Janub)',
    },
    LS: {
        C: 'Berea',
        A: 'Butha-Buthe',
        B: 'Leribe',
        E: 'Mafeteng',
        D: 'Maseru',
        F: 'Mohale’s Hoek',
        J: 'Mokhotlong',
        H: 'Qacha’s Nek',
        G: 'Quthing',
        K: 'Thaba-Tseka',
    },
    LR: {
        BM: 'Bomi',
        BG: 'Bong',
        GG: 'Gbarpolu',
        GB: 'Grand Bassa',
        CM: 'Grand Cape Mount',
        GM: 'Grand Gedeh',
        GK: 'Grand Kru',
        LO: 'Lofa',
        MG: 'Margibi',
        MY: 'Maryland',
        MO: 'Montserrado',
        NI: 'Nimba',
        RG: 'River Gee',
        RV: 'Rivercess',
        SN: 'Sinoe',
    },
    LY: {
        BA: 'Benghazi',
        BU: 'Butnan',
        DR: 'Derna',
        GT: 'Ghat',
        JA: 'Jabal al Akhdar',
        JB: 'Jabal al Gharbi',
        JG: 'Jafara',
        JI: 'Jufra',
        KF: 'Kufra',
        MJ: 'Marj',
        MB: 'Mbardi (possibly older code?)',
        MI: 'Misrata',
        MQ: 'Murqub',
        JU: 'Murzuq',
        NL: 'Nalut',
        SB: 'Sabha',
        SR: 'Sirte',
        TB: 'Tripoli',
        WA: 'Wadi al Hayaa',
        WQ: 'Wadi ash Shatii',
        ZA: 'Zawiya',
        ZW: 'Zwila (disputed older code?)',
    },
    LI: {
        L: 'Liechtenstein',
    },
    LT: {
        AL: 'Alytaus',
        KU: 'Kauno',
        KL: 'Klaipėdos',
        MR: 'Marijampolės',
        PN: 'Panevėžio',
        TA: 'Tauragės',
        TE: 'Telšių',
        UT: 'Utenos',
        VI: 'Vilniaus',
        SA: 'Šiaulių',
    },
    LU: {
        CA: 'Capellen',
        CL: 'Clervaux',
        DI: 'Diekirch',
        EC: 'Echternach',
        ES: 'Esch-sur-Alzette',
        GR: 'Grevenmacher',
        LU: 'Luxembourg (canton)',
        ME: 'Mersch',
        RD: 'Redange',
        RM: 'Remich',
        VD: 'Vianden',
        WI: 'Wiltz',
    },
    MO: {
        M: 'Macao SAR',
    },
    MG: {
        T: 'Antananarivo',
        D: 'Antsiranana',
        F: 'Fianarantsoa',
        M: 'Mahajanga',
        A: 'Toamasina',
        U: 'Toliara',
    },
    MW: {
        C: 'Central Region',
        N: 'Northern Region',
        S: 'Southern Region',
    },
    MY: {
        '01': 'Johor',
        '02': 'Kedah',
        '03': 'Kelantan',
        '14': 'Kuala Lumpur',
        '15': 'Labuan',
        '04': 'Melaka (Malacca)',
        '05': 'Negeri Sembilan',
        '06': 'Pahang',
        '08': 'Perak',
        '09': 'Perlis',
        '07': 'Pulau Pinang (Penang)',
        '16': 'Putrajaya',
        '12': 'Sabah',
        '13': 'Sarawak',
        '10': 'Selangor',
        '11': 'Terengganu',
    },
    MV: {
        '01': 'Addu City (Seenu)',
        '28': 'Alif Alif',
        '29': 'Alif Dhaalu',
        '31': 'Baa',
        '32': 'Dhaalu',
        '02': 'Faafu',
        '03': 'Gaafu Alif',
        '04': 'Gaafu Dhaalu',
        '05': 'Gnaviyani',
        '07': 'Haa Alif',
        '08': 'Haa Dhaalu',
        '27': 'Kaafu',
        '12': 'Laamu',
        '13': 'Lhaviyani',
        '00': 'Malé',
        '14': 'Meemu',
        '17': 'Noonu',
        '20': 'Raa',
        '23': 'Shaviyani',
        '24': 'Thaa',
        '25': 'Vaavu',
    },
    ML: {
        BKO: 'Bamako (Capital District)',
        '7': 'Gao',
        '1': 'Kayes',
        '8': 'Kidal',
        '2': 'Koulikoro',
        '5': 'Mopti',
        '10': 'Ménaka',
        '3': 'Sikasso',
        '4': 'Ségou',
        '9': 'Taoudénit',
        '6': 'Tombouctou',
    },
    MT: {
        M: 'Malta',
    },
    MH: {
        MI: 'Marshall Islands',
    },
    MQ: {
        M: 'Martinique',
    },
    MR: {
        '07': 'Adrar',
        '03': 'Assaba',
        '05': 'Brakna',
        '08': 'Dakhlet Nouadhibou',
        '04': 'Gorgol',
        '10': 'Guidimaka',
        '01': 'Hodh ech Chargui',
        '02': 'Hodh el Gharbi',
        '12': 'Inchiri',
        '14': 'Nouakchott Nord',
        '13': 'Nouakchott Ouest',
        '15': 'Nouakchott Sud',
        '09': 'Tagant',
        '11': 'Tiris Zemmour',
        '06': 'Trarza',
    },
    MU: {
        AG: 'Agalega Islands',
        BL: 'Black River',
        CC: 'Cargados Carajos Shoals (Saint Brandon)',
        FL: 'Flacq',
        GP: 'Grand Port',
        MO: 'Moka',
        PA: 'Pamplemousses',
        PW: 'Plaines Wilhems',
        PL: 'Port Louis',
        QB: 'Quatre Bornes (sometimes used as local authority)',
        RR: 'Rivière du Rempart',
        SA: 'Savanne',
        VP: 'Vacoas-Phoenix (sometimes local authority)',
    },
    YT: {
        M: 'Mayotte',
    },
    MX: {
        AGU: 'Aguascalientes',
        BCN: 'Baja California',
        BCS: 'Baja California Sur',
        CAM: 'Campeche',
        CHP: 'Chiapas',
        CHH: 'Chihuahua',
        CMX: 'Ciudad de México (Mexico City)',
        COA: 'Coahuila de Zaragoza',
        COL: 'Colima',
        DUR: 'Durango',
        GUA: 'Guanajuato',
        GRO: 'Guerrero',
        HID: 'Hidalgo',
        JAL: 'Jalisco',
        MIC: 'Michoacán de Ocampo',
        MOR: 'Morelos',
        MEX: 'México (State of Mexico)',
        NAY: 'Nayarit',
        NLE: 'Nuevo León',
        OAX: 'Oaxaca',
        PUE: 'Puebla',
        QUE: 'Querétaro',
        ROO: 'Quintana Roo',
        SLP: 'San Luis Potosí',
        SIN: 'Sinaloa',
        SON: 'Sonora',
        TAB: 'Tabasco',
        TAM: 'Tamaulipas',
        TLA: 'Tlaxcala',
        VER: 'Veracruz de Ignacio de la Llave',
        YUC: 'Yucatán',
        ZAC: 'Zacatecas',
    },
    FM: {
        CHK: 'Chuuk',
        KSA: 'Kosrae',
        PNI: 'Pohnpei',
        YAP: 'Yap',
    },
    MD: {
        AN: 'Anenii Noi',
        BA: 'Basarabeasca',
        BR: 'Briceni',
        BS: 'Bălți (Municipality)',
        CA: 'Cahul',
        CT: 'Cantemir',
        CS: 'Chișinău (Municipality)',
        CU: 'Chișinău (older code?), check duplicates',
        CM: 'Cimișlia',
        CR: 'Criuleni',
        CL: 'Călărași',
        DO: 'Dondușeni',
        DR: 'Drochia',
        ED: 'Edineț',
        FL: 'Florești',
        FA: 'Fălești',
        GL: 'Glodeni',
        GA: 'Găgăuzia (Autonomous Territorial Unit)',
        HI: 'Hîncești',
        IA: 'Ialoveni',
        LE: 'Leova',
        NI: 'Nisporeni',
        OC: 'Ocnița',
        OR: 'Orhei',
        RE: 'Rezina',
        RI: 'Rîșcani',
        SO: 'Soroca',
        ST: 'Strășeni',
        SD: 'Stânga Nistrului (Transnistria, disputed)',
        SI: 'Sîngerei',
        TA: 'Taraclia',
        TE: 'Telenești',
        BD: 'Tighina (Bender, Municipality)',
        UN: 'Ungheni',
        SV: 'Șoldănești',
    },
    MC: {
        M: 'Monaco',
    },
    MN: {
        '073': 'Arkhangai',
        '071': 'Bayan-Ölgiy',
        '069': 'Bayanhongor',
        '067': 'Bulgan',
        '037': 'Darhan uul',
        '061': 'Dornod',
        '063': 'Dornogovi',
        '059': 'Dundgovi',
        '057': 'Dzavhan',
        '065': 'Govi-Altay',
        '064': 'Govi-Sumber',
        '039': 'Hentiy',
        '043': 'Hovd',
        '041': 'Hövsgöl',
        '035': 'Orhon',
        '049': 'Selenge',
        '051': 'Sühbaatar',
        '047': 'Töv',
        '1': 'Ulaanbaatar (municipality)',
        '046': 'Uvs',
        '053': 'Ömnögovi',
        '055': 'Övörhangay',
    },
    ME: {
        '01': 'Andrijevica',
        '02': 'Bar',
        '03': 'Berane',
        '04': 'Bijelo Polje',
        '05': 'Budva',
        '06': 'Cetinje',
        '07': 'Danilovgrad',
        '08': 'Gusinje',
        '09': 'Herceg Novi',
        '10': 'Kolašin',
        '11': 'Kotor',
        '12': 'Mojkovac',
        '13': 'Nikšić',
        '14': 'Petnjica',
        '15': 'Plav',
        '16': 'Pljevlja',
        '17': 'Plužine',
        '18': 'Podgorica',
        '19': 'Rožaje',
        '21': 'Tivat',
        '24': 'Tuzi (new municipality)',
        '22': 'Ulcinj',
        '20': 'Šavnik',
        '23': 'Žabljak',
    },
    MS: {
        M: 'Montserrat',
    },
    MA: {
        '05': 'Béni Mellal-Khénifra',
        '06': 'Casablanca-Settat',
        '12': 'Dakhla-Oued Ed-Dahab',
        '08': 'Drâa-Tafilalet',
        '03': 'Fès-Meknès',
        '10': 'Guelmim-Oued Noun',
        '11': 'Laâyoune-Sakia El Hamra',
        '02': 'L’Oriental',
        '07': 'Marrakech-Safi',
        '04': 'Rabat-Salé-Kénitra',
        '09': 'Souss-Massa',
        '01': 'Tanger-Tétouan-Al Hoceïma',
    },
    MZ: {
        P: 'Cabo Delgado',
        G: 'Gaza',
        I: 'Inhambane',
        B: 'Manica',
        MPM: 'Maputo (city)',
        L: 'Maputo (province)',
        N: 'Nampula',
        A: 'Niassa',
        S: 'Sofala',
        T: 'Tete',
        Q: 'Zambézia',
    },
    MM: {
        '07': 'Ayeyarwady',
        '02': 'Bago',
        '14': 'Chin',
        '11': 'Kachin',
        '12': 'Kayah',
        '13': 'Kayin',
        '03': 'Magway',
        '04': 'Mandalay',
        '15': 'Mon',
        '18': 'Naypyidaw (Union Territory)',
        '16': 'Rakhine',
        '01': 'Sagaing',
        '17': 'Shan',
        '05': 'Tanintharyi',
        '06': 'Yangon',
    },
    NA: {
        ER: 'Erongo',
        HA: 'Hardap',
        KA: 'Karas (now ǁKaras)',
        KE: 'Kavango East',
        KW: 'Kavango West',
        KH: 'Khomas',
        KU: 'Kunene',
        OH: 'Ohangwena',
        ON: 'Omaheke',
        OS: 'Omusati',
        OM: 'Oshana',
        OK: 'Oshikoto',
        OT: 'Otjozondjupa',
        CA: 'Zambezi (formerly Caprivi)',
    },
    NR: {
        N: 'Nauru',
    },
    NP: {
        P3: 'Bagmati Province',
        P4: 'Gandaki Province',
        P6: 'Karnali Province',
        P5: 'Lumbini Province',
        P2: 'Madhesh Province',
        P1: 'Province 1',
        P7: 'Sudurpashchim Province',
    },
    NL: {
        DR: 'Drenthe',
        FL: 'Flevoland',
        FR: 'Fryslân',
        GE: 'Gelderland',
        GR: 'Groningen',
        LI: 'Limburg',
        NB: 'Noord-Brabant',
        NH: 'Noord-Holland',
        OV: 'Overijssel',
        UT: 'Utrecht',
        ZE: 'Zeeland',
        ZH: 'Zuid-Holland',
    },
    NC: {
        NC: 'New Caledonia',
    },
    NZ: {
        AUK: 'Auckland',
        BOP: 'Bay of Plenty',
        CAN: 'Canterbury',
        CIT: 'Chatham Islands Territory',
        GIS: 'Gisborne',
        HKB: 'Hawke’s Bay',
        MWT: 'Manawatu-Wanganui',
        MBH: 'Marlborough',
        NSN: 'Nelson',
        NTL: 'Northland',
        OTA: 'Otago',
        STL: 'Southland',
        TKI: 'Taranaki',
        TAS: 'Tasman',
        WKO: 'Waikato',
        WGN: 'Wellington',
        WTC: 'West Coast',
    },
    NI: {
        AN: 'Atlántico Norte (RAAN, now Norte)',
        AS: 'Atlántico Sur (RAAS, now Sur)',
        BO: 'Boaco',
        CA: 'Carazo',
        CI: 'Chinandega',
        CO: 'Chontales',
        ES: 'Estelí',
        GR: 'Granada',
        JI: 'Jinotega',
        LE: 'León',
        MD: 'Madriz',
        MN: 'Managua',
        MS: 'Masaya',
        MT: 'Matagalpa',
        NS: 'Nueva Segovia',
        RI: 'Rivas',
        SC: 'Río San Juan (San Carlos in some references)',
    },
    NE: {
        '1': 'Agadez',
        '2': 'Diffa',
        '3': 'Dosso',
        '4': 'Maradi',
        '8': 'Niamey (Capital District)',
        '5': 'Tahoua',
        '6': 'Tillabéri',
        '7': 'Zinder',
    },
    NG: {
        AB: 'Abia',
        AD: 'Adamawa',
        AK: 'Akwa Ibom',
        AN: 'Anambra',
        BA: 'Bauchi',
        BY: 'Bayelsa',
        BE: 'Benue',
        BO: 'Borno',
        CR: 'Cross River',
        DE: 'Delta',
        EB: 'Ebonyi',
        ED: 'Edo',
        EK: 'Ekiti',
        EN: 'Enugu',
        FC: 'Federal Capital Territory (Abuja)',
        GO: 'Gombe',
        IM: 'Imo',
        JI: 'Jigawa',
        KD: 'Kaduna',
        KN: 'Kano',
        KT: 'Katsina',
        KE: 'Kebbi',
        KO: 'Kogi',
        KW: 'Kwara',
        LA: 'Lagos',
        NA: 'Nasarawa',
        NI: 'Niger',
        OG: 'Ogun',
        ON: 'Ondo',
        OS: 'Osun',
        OY: 'Oyo',
        PL: 'Plateau',
        RI: 'Rivers',
        SO: 'Sokoto',
        TA: 'Taraba',
        YO: 'Yobe',
        ZA: 'Zamfara',
    },
    NU: {
        N: 'Niue',
    },
    NF: {
        NI: 'Norfolk Island',
    },
    MK: {
        '01': 'Aerodrom',
        '02': 'Aračinovo',
        '03': 'Berovo',
        '04': 'Bitola',
        '05': 'Bogdanci',
        SK: 'Skopje (City)',
    },
    MP: {
        NI: 'Northern Mariana Islands',
    },
    NO: {
        '42': 'Agder',
        '02': 'Akershus (merged into Viken)',
        '09': 'Aust-Agder (merged into Agder)',
        '06': 'Buskerud (merged into Viken)',
        '20': 'Finnmark (merged into Troms og Finnmark)',
        '04': 'Hedmark (merged into Innlandet)',
        '12': 'Hordaland (merged into Vestland)',
        '34': 'Innlandet',
        '15': 'Møre og Romsdal',
        '18': 'Nordland',
        '05': 'Oppland (merged into Innlandet)',
        '03': 'Oslo',
        '11': 'Rogaland',
        '14': 'Sogn og Fjordane (merged into Vestland)',
        '08': 'Telemark (merged into Vestfold og Telemark)',
        '19': 'Troms (merged into Troms og Finnmark)',
        '54': 'Troms og Finnmark',
        '50': 'Trøndelag',
        '10': 'Vest-Agder (merged into Agder)',
        '07': 'Vestfold (merged into Vestfold og Telemark)',
        '38': 'Vestfold og Telemark',
        '46': 'Vestland',
        '30': 'Viken',
        '01': 'Østfold (merged into Viken in 2020)',
    },
    OM: {
        DA: 'Ad Dakhiliyah',
        ZA2: 'Ad Dhahirah',
        ZU: 'Adh Dhahirah ',
        BJ: 'Al Batinah North ',
        BK: 'Al Batinah South',
        BU: 'Al Buraymi',
        WU: 'Al Wusta',
        SH: 'Ash Sharqiyah North',
        SS: 'Ash Sharqiyah South',
        ZA: 'Az̧ Z̧āhirah',
        BS: 'Busaid',
        ZA3: 'Dhofar',
        MU: 'Musandam',
        MA: 'Muscat',
    },
    PK: {
        JK: 'Azad Jammu and Kashmir',
        BA: 'Balochistan',
        TA: 'Federally Administered Tribal Areas',
        GB: 'Gilgit-Baltistan',
        IS: 'Islamabad Capital Territory',
        KP: 'Khyber Pakhtunkhwa',
        PB: 'Punjab',
        SD: 'Sindh',
    },
    PW: {
        P: 'Palau',
    },
    PS: {
        BTH: 'Bethlehem',
        DEB: 'Deir al-Balah',
        GZA: 'Gaza',
        HBN: 'Hebron (Al Khalil)',
        JEN: 'Jenin',
        JRH: 'Jericho (Ariha)',
        JEM: 'Jerusalem (Al Quds)',
        KYS: 'Khan Yunis',
        NBS: 'Nablus',
        NGZ: 'North Gaza',
        QQA: 'Qalqilya',
        RFH: 'Rafah',
        RBH: 'Ramallah and Al-Bireh',
        SLT: 'Salfit',
        TBS: 'Tubas',
        TQM: 'Tulkarm',
    },
    PA: {
        '1': 'Bocas del Toro',
        '4': 'Chiriquí',
        '2': 'Coclé',
        '3': 'Colón',
        '5': 'Darién',
        EM: 'Emberá (Comarca)',
        KY: 'Guna Yala (Comarca)',
        '6': 'Herrera',
        '7': 'Los Santos',
        NB: 'Ngäbe-Buglé (Comarca)',
        '8': 'Panamá',
        '10': 'Panamá Oeste',
        '9': 'Veraguas',
        SB: 'Wargandí / Madugandí? (Details vary, often not in ISO yet)',
    },
    PG: {
        NSB: 'Bougainville (Autonomous Region)',
        CPM: 'Central',
        CPK: 'Chimbu (Simbu)',
        EBR: 'East New Britain',
        EPG: 'East Sepik',
        EHG: 'Eastern Highlands',
        EPW: 'Enga',
        GPK: 'Gulf',
        HLA: 'Hela',
        JWK: 'Jiwaka',
        MPM: 'Madang',
        MRL: 'Manus',
        MBA: 'Milne Bay',
        MPL: 'Morobe',
        NCD: 'National Capital District (Port Moresby)',
        NIK: 'New Ireland',
        NPP: 'Northern (Oro)',
        SIM: 'Simbu? (duplicate code for CPK, be careful)',
        SHM: 'Southern Highlands',
        WBK: 'West New Britain',
        SAN: 'West Sepik (Sandaun)',
        WPD: 'Western (Fly)',
        WHM: 'Western Highlands',
    },
    PY: {
        '16': 'Alto Paraguay',
        '10': 'Alto Paraná',
        '13': 'Amambay',
        ASU: 'Asunción (capital district)',
        '19': 'Boquerón',
        '5': 'Caaguazú',
        '6': 'Caazapá',
        '14': 'Canindeyú',
        '11': 'Central',
        '1': 'Concepción',
        '3': 'Cordillera',
        '4': 'Guairá',
        '7': 'Itapúa',
        '8': 'Misiones',
        '9': 'Paraguarí',
        '15': 'Presidente Hayes',
        '2': 'San Pedro',
        '12': 'Ñeembucú',
    },
    PE: {
        AMA: 'Amazonas',
        ANC: 'Ancash',
        APU: 'Apurímac',
        ARE: 'Arequipa',
        AYA: 'Ayacucho',
        CAJ: 'Cajamarca',
        CUS: 'Cusco',
        CAL: 'El Callao (constitutional province)',
        HUV: 'Huancavelica',
        HUC: 'Huánuco',
        ICA: 'Ica',
        JUN: 'Junín',
        LAL: 'La Libertad',
        LAM: 'Lambayeque',
        LIM: 'Lima (region)',
        LOR: 'Loreto',
        MDD: 'Madre de Dios',
        MOQ: 'Moquegua',
        LMA: 'Municipalidad Metropolitana de Lima (provincial municipality)',
        PAS: 'Pasco',
        PIU: 'Piura',
        PUN: 'Puno',
        SAM: 'San Martín',
        TAC: 'Tacna',
        TUM: 'Tumbes',
        UCA: 'Ucayali',
    },
    PH: {
        '14': 'Autonomous Region in Muslim Mindanao (old code, replaced by BARMM)',
        BARMM: 'Bangsamoro Autonomous Region in Muslim Mindanao',
        '05': 'Bicol Region (Region V)',
        '04': 'CALABARZON (Region IV-A)',
        '02': 'Cagayan Valley (Region II)',
        '13': 'Caraga (Region XIII)',
        '03': 'Central Luzon (Region III)',
        '07': 'Central Visayas (Region VII)',
        CAR: 'Cordillera Administrative Region',
        '11': 'Davao Region (Region XI)',
        '08': 'Eastern Visayas (Region VIII)',
        '01': 'Ilocos Region (Region I)',
        NCR: 'National Capital Region (Metro Manila)',
        '10': 'Northern Mindanao (Region X)',
        '12': 'SOCCSKSARGEN (Region XII)',
        '06': 'Western Visayas (Region VI)',
        '09': 'Zamboanga Peninsula (Region IX)',
    },
    PN: {
        PI: 'Pitcairn Islands',
    },
    PL: {
        DS: 'Dolnośląskie',
        KP: 'Kujawsko-Pomorskie',
        LU: 'Lubelskie',
        LB: 'Lubuskie',
        MZ: 'Mazowieckie',
        MA: 'Małopolskie',
        OP: 'Opolskie',
        PK: 'Podkarpackie',
        PD: 'Podlaskie',
        PM: 'Pomorskie',
        WN: 'Warmińsko-Mazurskie (ISO code "PL-WN" or "PL-28" older?)',
        WP: 'Wielkopolskie',
        ZP: 'Zachodniopomorskie',
        LD: 'Łódzkie',
        SL: 'Śląskie',
        ŚK: 'Świętokrzyskie (ISO code actually "SK"? Some references show "SW")',
    },
    PT: {
        '01': 'Aveiro',
        '02': 'Beja',
        '03': 'Braga',
        '04': 'Bragança',
        '05': 'Castelo Branco',
        '06': 'Coimbra',
        '08': 'Faro',
        '09': 'Guarda',
        '10': 'Leiria',
        '11': 'Lisboa',
        '12': 'Portalegre',
        '13': 'Porto',
        '30': 'Região Autónoma da Madeira',
        '20': 'Região Autónoma dos Açores',
        '14': 'Santarém',
        '15': 'Setúbal',
        '16': 'Viana do Castelo',
        '17': 'Vila Real',
        '18': 'Viseu',
        '07': 'Évora',
    },
    PR: {
        PR: 'Puerto Rico',
    },
    QA: {
        DA: 'Ad Dawhah (Doha)',
        KH: 'Al Khawr wa adh Dhakhīrah',
        WA: 'Al Wajbah? (older references?), check updates',
        WB: 'Al Wakrah',
        RA: 'Ar Rayyān',
        MS: 'Ash Shamāl',
        ZA: 'Az̧ Za‘āyin',
        US: 'Umm Şalāl',
    },
    RE: {
        R: 'Réunion',
    },
    RO: {
        AB: 'Alba',
        AR: 'Arad',
        AG: 'Argeș',
        BC: 'Bacău',
        BH: 'Bihor',
        BN: 'Bistrița-Năsăud',
        BT: 'Botoșani',
        BV: 'Brașov',
        BR: 'Brăila',
        B: 'București (Bucharest)',
        BZ: 'Buzău',
        CS: 'Caraș-Severin',
        CJ: 'Cluj',
        CT: 'Constanța',
        CV: 'Covasna',
        CL: 'Călărași',
        DJ: 'Dolj',
        DB: 'Dâmbovița',
        GL: 'Galați',
        GR: 'Giurgiu',
        GJ: 'Gorj',
        HR: 'Harghita',
        HD: 'Hunedoara',
        IL: 'Ialomița',
        IS: 'Iași',
        IF: 'Ilfov',
        MM: 'Maramureș',
        MH: 'Mehedinți',
        MS: 'Mureș',
        NT: 'Neamț',
        OT: 'Olt',
        PH: 'Prahova',
        SM: 'Satu Mare',
        SB: 'Sibiu',
        SV: 'Suceava',
        SJ: 'Sălaj',
        TR: 'Teleorman',
        TM: 'Timiș',
        TL: 'Tulcea',
        VS: 'Vaslui',
        VN: 'Vrancea',
        VL: 'Vâlcea',
    },
    RW: {
        '01': 'City of Kigali',
        '02': 'Eastern Province',
        '03': 'Northern Province',
        '05': 'Southern Province',
        '04': 'Western Province',
    },
    BL: {
        SB: 'Saint Barthélemy',
    },
    SH: {
        SH: 'Saint Helena, Ascension and Tristan da Cunha',
    },
    KN: {
        'KN-N': 'Nevis',
        'KN-K': 'Saint Kitts',
    },
    LC: {
        SL: 'Saint Lucia',
    },
    MF: {
        SM: 'Saint Martin (French part)',
    },
    PM: {
        SP: 'Saint Pierre and Miquelon',
    },
    VC: {
        SV: 'Saint Vincent and the Grenadines',
    },
    WS: {
        S: 'Samoa',
    },
    SM: {
        SM: 'San Marino',
    },
    ST: {
        ST: 'Sao Tome and Principe',
    },
    SA: {
        '11': 'Al Bāhah',
        '12': 'Al Jawf',
        '03': 'Al Madīnah',
        '05': 'Al Qaşim',
        '01': 'Ar Riyāḍ',
        '04': 'Eastern Province (Ash Sharqīyah)',
        '09': 'Jīzān',
        '02': 'Makkah',
        '10': 'Najrān',
        '08': 'Northern Borders (Al Ḥudūd ash Shamāliyah)',
        '07': 'Tabūk',
        '06': 'Ḥāʼil',
        '14': '‘Asīr',
    },
    SN: {
        DK: 'Dakar',
        DB: 'Diourbel',
        FK: 'Fatick',
        KA: 'Kaffrine',
        KL: 'Kaolack',
        KD: 'Kolda',
        KE: 'Kédougou',
        LG: 'Louga',
        ML: 'Mali (older code? Not official in new references)',
        MT: 'Matam',
        SL: 'Saint-Louis',
        SE: 'Sédhiou',
        TC: 'Tambacounda',
        TH: 'Thiès',
        ZG: 'Ziguinchor',
    },
    RS: {
        '00': 'Belgrade (Beograd)',
        '14': 'Bor',
        '11': 'Braničevo',
        '02': 'Central Banat',
        '23': 'Jablanica',
        '09': 'Kolubara',
        '25': 'Kosovo',
        '29': 'Kosovo-Pomoravlje',
        '28': 'Kosovska Mitrovica',
        '08': 'Mačva',
        '17': 'Moravica',
        '20': 'Nišava',
        '03': 'North Banat',
        '01': 'North Bačka',
        '26': 'Peć',
        '22': 'Pirot',
        '10': 'Podunavlje',
        '13': 'Pomoravlje',
        '27': 'Prizren',
        '24': 'Pčinja',
        '19': 'Rasina',
        '18': 'Raška',
        '04': 'South Banat',
        '06': 'South Bačka',
        '07': 'Srem',
        '21': 'Toplica',
        '05': 'West Bačka',
        '15': 'Zaječar',
        '16': 'Zlatibor',
        '12': 'Šumadija',
    },
    SC: {
        '02': 'Anse Boileau',
        '03': 'Anse Etoile',
        '05': 'Anse Royale',
        '01': 'Anse aux Pins',
        '04': 'Au Cap',
        '06': 'Baie Lazare',
        '07': 'Baie Sainte Anne',
        '08': 'Beau Vallon',
        '09': 'Bel Air',
        '10': 'Bel Ombre',
        '11': 'Cascade',
        '16': 'English River (Mont Fleuri older name?)',
        '12': 'Glacis',
        '13': 'Grand’Anse Mahe',
        '14': 'Grand’Anse Praslin',
        '15': 'La Digue and Inner Islands',
        '17': 'Mont Buxton',
        '18': 'Plaisance',
        '19': 'Pointe La Rue',
        '20': 'Port Glaud',
        '21': 'Roche Caïman',
        '22': 'Saint Louis',
        '23': 'Takamaka',
    },
    SL: {
        E: 'Eastern Province',
        NW: 'North Western Province',
        N: 'Northern Province',
        S: 'Southern Province',
        W: 'Western Area',
    },
    SG: {
        S: 'Singapore',
    },
    SX: {
        SM: 'Sint Maarten (Dutch part)',
    },
    SK: {
        BC: 'Banskobystrický kraj',
        BL: 'Bratislavský kraj',
        KI: 'Košický kraj',
        NI: 'Nitriansky kraj',
        PV: 'Prešovský kraj',
        TC: 'Trenčiansky kraj',
        TA: 'Trnavský kraj',
        ZI: 'Žilinský kraj',
    },
    SI: {
        '001': 'Ajdovščina, Goriška (older references may differ)',
        '002': 'Beltinci, Pomurska',
    },
    SB: {
        CE: 'Central',
        CH: 'Choiseul',
        GC: 'Guadalcanal',
        HO: 'Honiara (capital territory)',
        IS: 'Isabel',
        MK: 'Makira-Ulawa',
        ML: 'Malaita',
        RB: 'Rennell and Bellona',
        TE: 'Temotu',
        WE: 'Western',
    },
    SO: {
        AW: 'Awdal',
        BK: 'Bakool',
        BN: 'Banaadir (Mogadishu)',
        BR: 'Bari',
        BY: 'Bay',
        GA: 'Galguduud',
        GE: 'Gedo',
        HI: 'Hiiraan',
        JD: 'Jubbada Dhexe (Middle Juba)',
        JH: 'Jubbada Hoose (Lower Juba)',
        MU: 'Mudug',
        NU: 'Nugaal',
        SA: 'Sanaag',
        SD: 'Shabeellaha Dhexe (Middle Shabelle)',
        SH: 'Shabeellaha Hoose (Lower Shabelle)',
        SL: 'Sool',
        TO: 'Togdheer',
        WO: 'Woqooyi Galbeed',
    },
    ZA: {
        EC: 'Eastern Cape',
        FS: 'Free State',
        GT: 'Gauteng',
        KZN: 'KwaZulu-Natal',
        LP: 'Limpopo',
        MP: 'Mpumalanga',
        NW: 'North West',
        NC: 'Northern Cape',
        WC: 'Western Cape',
    },
    GS: {
        SG: 'South Georgia and the South Sandwich Islands',
    },
    SS: {
        EC: 'Central Equatoria',
        EE: 'Eastern Equatoria',
        JG: 'Jonglei',
        LK: 'Lakes',
        BN: 'Northern Bahr el Ghazal',
        UY: 'Unity',
        NU: 'Upper Nile',
        WR: 'Warrap',
        BW: 'Western Bahr el Ghazal',
        EW: 'Western Equatoria',
    },
    ES: {
        AN: 'Andalucía',
        AR: 'Aragón',
        AS: 'Asturias (Principado de Asturias)',
        CN: 'Canarias',
        CB: 'Cantabria',
        CL: 'Castilla y León',
        CM: 'Castilla-La Mancha',
        CT: 'Cataluña (Catalunya)',
        CE: 'Ceuta',
        VC: 'Comunidad Valenciana',
        EX: 'Extremadura',
        GA: 'Galicia',
        IB: 'Islas Baleares',
        RI: 'La Rioja',
        MA: 'Madrid (Comunidad de)',
        ML: 'Melilla',
        MC: 'Murcia (Región de)',
        NC: 'Navarra (Comunidad Foral de)',
        PV: 'País Vasco (Euskadi)',
    },
    LK: {
        '2': 'Central',
        '5': 'Eastern',
        '7': 'North Central',
        '6': 'North Western',
        '4': 'Northern',
        '9': 'Sabaragamuwa',
        '3': 'Southern',
        '8': 'Uva',
        '1': 'Western',
    },
    SD: {
        NB: 'Blue Nile (An Nīl al Azraq)',
        DC: 'Central Darfur',
        DE: 'East Darfur',
        GD: 'Gedaref (Al Qadarif)',
        GZ: 'Gezira (Al Jazirah)',
        KA: 'Kassala',
        KN: 'Khartoum (Al Kharṭūm)',
        DN: 'North Darfur',
        KS: 'North Kordofan (Shamāl Kurdufān)',
        NO: 'Northern',
        RS: 'Red Sea (Al Baḥr al Aḥmar)',
        NR: 'River Nile (An Nīl)',
        SI: 'Sennar (Sinnār)',
        DS: 'South Darfur',
        SK: 'South Kordofan (Janūb Kurdufān)',
        DW: 'West Darfur',
        KW: 'West Kordofan (Gharb Kurdufān)',
        NW: 'White Nile (An Nīl al Abyaḍ)',
    },
    SR: {
        BR: 'Brokopondo',
        CM: 'Commewijne',
        CR: 'Coronie',
        MA: 'Marowijne',
        NI: 'Nickerie',
        PR: 'Para',
        PM: 'Paramaribo',
        SA: 'Saramacca',
        SI: 'Sipaliwini',
        WA: 'Wanica',
    },
    SJ: {
        S: 'Svalbard and Jan Mayen',
    },
    SE: {
        K: 'Blekinge län',
        W: 'Dalarnas län',
        I: 'Gotlands län',
        X: 'Gävleborgs län',
        N: 'Hallands län',
        Z: 'Jämtlands län',
        F: 'Jönköpings län',
        H: 'Kalmar län',
        G: 'Kronobergs län',
        BD: 'Norrbottens län',
        M: 'Skåne län',
        AB: 'Stockholms län',
        D: 'Södermanlands län',
        C: 'Uppsala län',
        S: 'Värmlands län',
        AC: 'Västerbottens län',
        Y: 'Västernorrlands län',
        U: 'Västmanlands län',
        O: 'Västra Götalands län',
        T: 'Örebro län',
        E: 'Östergötlands län',
    },
    CH: {
        AG: 'Aargau',
        AR: 'Appenzell Ausserrhoden',
        AI: 'Appenzell Innerrhoden',
        BL: 'Basel-Landschaft',
        BS: 'Basel-Stadt',
        BE: 'Bern / Berne',
        FR: 'Fribourg',
        GE: 'Genève',
        GL: 'Glarus',
        GR: 'Graubünden / Grisons',
        JU: 'Jura',
        LU: 'Luzern',
        NE: 'Neuchâtel',
        NW: 'Nidwalden',
        OW: 'Obwalden',
        SG: 'Sankt Gallen',
        SH: 'Schaffhausen',
        SZ: 'Schwyz',
        SO: 'Solothurn',
        TG: 'Thurgau',
        TI: 'Ticino',
        UR: 'Uri',
        VS: 'Valais / Wallis',
        VD: 'Vaud',
        ZG: 'Zug',
        ZH: 'Zürich',
    },
    TW: {
        CHA: 'Changhua',
        CYI: 'Chiayi City',
        CYQ: 'Chiayi County',
        HSZ: 'Hsinchu City',
        HSQ: 'Hsinchu County',
        HUA: 'Hualien',
        KHH: 'Kaohsiung',
        KEE: 'Keelung',
        MIA: 'Miaoli',
        NAN: 'Nantou',
        PEN: 'Penghu',
        PIF: 'Pingtung',
        TXG: 'Taichung',
        TNN: 'Tainan',
        TPE: 'Taipei',
        TTT: 'Taitung',
        TAO: 'Taoyuan',
        ILA: 'Yilan',
        YUN: 'Yunlin',
    },
    TJ: {
        RA: 'Districts of Republican Subordination (various districts)',
        DU: 'Dushanbe (capital)',
        GB: 'Gorno-Badakhshan (Kuhistoni Badakhshon)',
        KT: 'Khatlon',
        SU: 'Sughd',
    },
    TZ: {
        '01': 'Arusha',
        '02': 'Dar es Salaam',
        '03': 'Dodoma',
        '25': 'Geita',
        '04': 'Iringa',
        '05': 'Kagera',
        '06': 'Kaskazini Pemba',
        '07': 'Kaskazini Unguja',
        '26': 'Katavi',
        '08': 'Kigoma',
        '09': 'Kilimanjaro',
        '30': 'Kusini Pemba',
        '31': 'Kusini Unguja',
        '10': 'Lindi',
        '24': 'Manyara',
        '11': 'Mara',
        '12': 'Mbeya',
        '13': 'Mjini Magharibi',
        '14': 'Morogoro',
        '15': 'Mtwara',
        '16': 'Mwanza',
        '27': 'Njombe',
        '17': 'Pwani (Coast)',
        '18': 'Rukwa',
        '19': 'Ruvuma',
        '20': 'Shinyanga',
        '28': 'Simiyu',
        '21': 'Singida',
        '29': 'Songwe',
        '22': 'Tabora',
        '23': 'Tanga',
    },
    TH: {
        '15': 'Ang Thong',
        '10': 'Bangkok (Krung Thep Maha Nakhon)',
        '12': 'Nonthaburi',
        '13': 'Pathum Thani',
        '14': 'Phra Nakhon Si Ayutthaya',
        '11': 'Samut Prakan',
    },
    TL: {
        AL: 'Aileu',
        AN: 'Ainaro',
        BA: 'Baucau',
        BO: 'Bobonaro',
        CO: 'Cova Lima',
        DI: 'Dili',
        ER: 'Ermera',
        LA: 'Lautém',
        LI: 'Liquiçá',
        MT: 'Manatuto',
        MF: 'Manufahi',
        OE: 'Oecusse (special region)',
        VI: 'Viqueque',
    },
    TG: {
        C: 'Centrale',
        K: 'Kara',
        M: 'Maritime',
        P: 'Plateaux',
        S: 'Savanes',
    },
    TK: {
        T: 'Tokelau',
    },
    TO: {
        T: 'Tonga',
    },
    TT: {
        ARI: 'Arima (Borough)',
        CHA: 'Chaguanas (Borough)',
        CTT: 'Couva–Tabaquite–Talparo (Region)',
        DMN: 'Diego Martin (Region)',
        PED: 'Penal–Debe (Region)',
        PTF: 'Point Fortin (Borough)',
        POS: 'Port of Spain (City)',
        PRT: 'Princes Town (Region)',
        RCM: 'Rio Claro–Mayaro (Region)',
        SFO: 'San Fernando (City)',
        SGE: 'Sangre Grande (Region)',
        SIP: 'Siparia (Region)',
        TOB: 'Tobago (Ward)',
        TUP: 'Tunapuna–Piarco (Region)',
    },
    TN: {
        '13': 'Ben Arous',
        '23': 'Bizerte',
        '31': 'Béja',
        '81': 'Gabès',
        '71': 'Gafsa',
        '32': 'Jendouba',
        '41': 'Kairouan',
        '42': 'Kasserine',
        '73': 'Kébili',
        '14': 'La Manouba',
        '33': 'Le Kef',
        '12': 'L’Ariana',
        '53': 'Mahdia',
        '52': 'Monastir',
        '82': 'Médnine',
        '21': 'Nabeul',
        '61': 'Sfax',
        '43': 'Sidi Bouzid',
        '34': 'Siliana',
        '51': 'Sousse',
        '83': 'Tataouine',
        '72': 'Tozeur',
        '11': 'Tunis',
        '22': 'Zaghouan',
    },
    TR: {
        '01': 'Adana',
        '02': 'Adıyaman',
        '03': 'Afyonkarahisar',
        '05': 'Amasya',
        '04': 'Ağrı',
    },
    TM: {
        A: 'Ahal',
        S: 'Aşgabat (capital city, sometimes “Ashgabat”)',
        B: 'Balkan',
        D: 'Daşoguz',
        L: 'Lebap',
        M: 'Mary',
    },
    TC: {
        T: 'Turks and Caicos Islands',
    },
    TV: {
        T: 'Tuvalu',
    },
    UG: {
        C: 'Central Region',
        E: 'Eastern Region',
        N: 'Northern Region',
        W: 'Western Region',
    },
    UA: {
        '71': 'Cherkaska oblast',
        '74': 'Chernihivska oblast',
        '77': 'Chernivetska oblast',
        '12': 'Dnipropetrovska oblast',
        '14': 'Donetska oblast (partly disputed)',
        '26': 'Ivano-Frankivska oblast',
        '63': 'Kharkivska oblast',
        '65': 'Khersonska oblast (partly disputed)',
        '68': 'Khmelnytska oblast',
        '35': 'Kirovohradska oblast',
        '30': 'Kyiv (special status city)',
        '32': 'Kyivska oblast',
        '09': 'Luhanska oblast (partly disputed)',
        '46': 'Lvivska oblast',
        '48': 'Mykolaivska oblast',
        '51': 'Odeska oblast',
        '53': 'Poltavska oblast',
        '43': 'Respublika Krym (Crimea, disputed)',
        '56': 'Rivnenska oblast',
        '59': 'Sumska oblast',
        '61': 'Ternopilska oblast',
        '05': 'Vinnytska oblast',
        '07': 'Volynska oblast',
        '21': 'Zakarpatska oblast',
        '23': 'Zaporizka oblast',
        '18': 'Zhytomyrska oblast',
    },
    AE: {
        AZ: 'Abū Z̧aby (Abu Dhabi)',
        FU: 'Al Fujayrah',
        SH: 'Ash Shāriqah (Sharjah)',
        DU: 'Dubayy (Dubai)',
        RK: 'Ra’s al Khaymah',
        UQ: 'Umm al Qaywayn',
        AJ: 'ʻAjmān',
    },
    GB: {
        EMD: 'East Midlands',
        EAE: 'East of England',
        GLN: 'Greater London',
        NET: 'North East',
        NWM: 'North West',
        NIR: 'Northern Ireland',
        SCT: 'Scotland',
        SE: 'South East',
        SW: 'South West',
        WLS: 'Wales',
        WM: 'West Midlands',
        YHU: 'Yorkshire and the Humber',
    },
    UM: {
        US: 'United States Minor Outlying Islands',
    },
    US: {
        AL: 'Alabama',
        AK: 'Alaska',
        AZ: 'Arizona',
        AR: 'Arkansas',
        CA: 'California',
        CO: 'Colorado',
        CT: 'Connecticut',
        DE: 'Delaware',
        FL: 'Florida',
        GA: 'Georgia',
        HI: 'Hawaii',
        ID: 'Idaho',
        IL: 'Illinois',
        IN: 'Indiana',
        IA: 'Iowa',
        KS: 'Kansas',
        KY: 'Kentucky',
        LA: 'Louisiana',
        ME: 'Maine',
        MD: 'Maryland',
        MA: 'Massachusetts',
        MI: 'Michigan',
        MN: 'Minnesota',
        MS: 'Mississippi',
        MO: 'Missouri',
        MT: 'Montana',
        NE: 'Nebraska',
        NV: 'Nevada',
        NH: 'New Hampshire',
        NJ: 'New Jersey',
        NM: 'New Mexico',
        NY: 'New York',
        NC: 'North Carolina',
        ND: 'North Dakota',
        OH: 'Ohio',
        OK: 'Oklahoma',
        OR: 'Oregon',
        PA: 'Pennsylvania',
        RI: 'Rhode Island',
        SC: 'South Carolina',
        SD: 'South Dakota',
        TN: 'Tennessee',
        TX: 'Texas',
        UT: 'Utah',
        VT: 'Vermont',
        VA: 'Virginia',
        WA: 'Washington',
        WV: 'West Virginia',
        WI: 'Wisconsin',
        WY: 'Wyoming',
    },
    UY: {
        AR: 'Artigas',
        CA: 'Canelones',
        CL: 'Cerro Largo',
        CO: 'Colonia',
        DU: 'Durazno',
        FS: 'Flores',
        FD: 'Florida',
        LA: 'Lavalleja',
        MA: 'Maldonado',
        MO: 'Montevideo',
        PA: 'Paysandú',
        RV: 'Rivera',
        RO: 'Rocha',
        RN: 'Río Negro',
        SA: 'Salto',
        SJ: 'San José',
        SO: 'Soriano',
        TA: 'Tacuarembó',
        TT: 'Treinta y Tres',
    },
    UZ: {
        AN: 'Andijon',
        BU: 'Buxoro',
        FA: 'Farg‘ona',
        JI: 'Jizzax',
        NG: 'Namangan',
        NW: 'Navoiy',
        QA: 'Qashqadaryo',
        QR: 'Qoraqalpog‘iston (Karakalpakstan, autonomous republic)',
        SA: 'Samarqand',
        SI: 'Sirdaryo',
        SU: 'Surxondaryo',
        TO: 'Toshkent (city)',
        TK: 'Toshkent (region)',
        KH: 'Xorazm',
    },
    VU: {
        VU: 'Vanuatu',
    },
    VE: {
        Z: 'Amazonas',
        B: 'Anzoátegui',
        C: 'Apure',
        D: 'Aragua',
        E: 'Barinas',
        F: 'Bolívar',
        G: 'Carabobo',
        A: 'Caracas (Distrito Capital)',
        H: 'Cojedes',
        Y: 'Delta Amacuro',
        W: 'Dependencias Federales (Federal Dependencies)',
        I: 'Falcón',
        J: 'Guárico',
        K: 'Lara',
        M: 'Miranda',
        N: 'Monagas',
        L: 'Mérida',
        O: 'Nueva Esparta',
        P: 'Portuguesa',
        R: 'Sucre',
        T: 'Trujillo',
        S: 'Táchira',
        X: 'Vargas (La Guaira)',
        U: 'Yaracuy',
        V: 'Zulia',
    },
    VN: {
        '04': 'Cao Bằng',
        '03': 'Hà Giang',
        '01': 'Lai Châu',
        '02': 'Lào Cai',
        '05': 'Sơn La',
    },
    WF: {
        '': 'Wallis and Futuna',
    },
    VI: {
        '': 'Wallis and Futuna',
    },
    VG: {
        '': 'Wallis and Futuna',
    },
    EH: {
        '': 'Wallis and Futuna',
    },
    YE: {
        AD: 'Adan (Aden)',
        AB: 'Abyan',
        DA: 'Ad Dāli‘',
        BA: 'Al Bayḑā’',
        JA: 'Al Jawf',
        MR: 'Al Mahrah',
        MW: 'Al Maḩwīt',
        HU: 'Al Ḩudaydah',
        SA: 'Amānat al ‘Āşimah (Sanaa Municipality)',
        DH: 'Dhamār',
        IB: 'Ibb',
        LA: 'Laḥij',
        MA: 'Ma’rib',
        RA: 'Raymah',
        SN: 'Sana’a (the surrounding governorate)',
        SH: 'Shabwah',
        SU: 'Socotra (Soqatra) - *sometimes part of Ḥaḑramawt or a separate area?',
        TA: 'Tāʻizz',
        SD: 'Şāʻdah',
        HJ: 'Ḥajjah',
        HD: 'Ḥaḑramawt',
        AM: '‘Amrān',
    },
    ZM: {
        '02': 'Central',
        '08': 'Copperbelt',
        '03': 'Eastern',
        '04': 'Luapula',
        '09': 'Lusaka',
        '10': 'Muchinga',
        '06': 'North-Western',
        '05': 'Northern',
        '07': 'Southern',
        '01': 'Western',
    },
    ZW: {
        BU: 'Bulawayo (city)',
        HA: 'Harare (city)',
        MA: 'Manicaland',
        MC: 'Mashonaland Central',
        ME: 'Mashonaland East',
        MH: 'Mashonaland West',
        MV: 'Masvingo',
        MN: 'Matabeleland North',
        MS: 'Matabeleland South',
        MI: 'Midlands',
    },
};

const LANGUAGE = {
    'ab-GE': 'Abkhazian',
    'aa-ET': 'Afar',
    'af-ZA': 'Afrikaans',
    'ak-GH': 'Akan',
    'sq-AL': 'Albanian',
    'am-ET': 'Amharic',
    'ar-SA': 'Arabic',
    'an-ES': 'Aragonese',
    'hy-AM': 'Armenian',
    'as-IN': 'Assamese',
    'av-RU': 'Avaric',
    'ae-IR': 'Avestan',
    'ay-BO': 'Aymara',
    'az-AZ': 'Azerbaijani',
    'bm-ML': 'Bambara',
    'ba-RU': 'Bashkir',
    'eu-ES': 'Basque',
    'be-BY': 'Belarusian',
    'fr-BE': 'Belgian French',
    'bn-BD': 'Bengali',
    'bh-IN': 'Bihari',
    'bi-VU': 'Bislama',
    'bs-YU': 'Bosnian',
    'pt-BR': 'Brazilian Portuguese',
    'br-FR': 'Breton',
    'bg-BG': 'Bulgarian',
    'my-MM': 'Burmese',
    'fr-CA': 'Canadian French',
    'ca-ES': 'Catalan',
    'ch-GU': 'Chamorro',
    'ce-RU': 'Chechen',
    'ny-MW': 'Chichewa',
    'cu-RU': 'Church Slavic',
    'cv-RU': 'Chuvash',
    'kw-GB': 'Cornish',
    'co-FR': 'Corsican',
    'cr-CA': 'Cree',
    'hr-HR': 'Croatian',
    'cs-CZ': 'Czech',
    'da-DK': 'Danish',
    'dv-MV': 'Divehi',
    'nl-NL': 'Dutch',
    'dz-BT': 'Dzongkha',
    'en-US': 'English (US)',
    'en-AU': 'English (Australian)',
    'en-GB': 'English (UK)',
    'eo-FR': 'Esperanto',
    'et-EE': 'Estonian',
    'ee-GH': 'Ewe',
    'fo-FO': 'Faroese',
    'fj-FJ': 'Fijian',
    'fi-FI': 'Finnish',
    'nl-BE': 'Flemish',
    'fr-FR': 'French',
    'fr-CH': 'French (Switzerland)',
    'fy-NL': 'Frisian',
    'ff-NG': 'Fulah',
    'gl-ES': 'Gallegan',
    'lg-UG': 'Ganda',
    'ka-GE': 'Georgian',
    'de-DE': 'German',
    'de-AT': 'German (Austria)',
    'de-CH': 'German (Switzerland)',
    'el-GR': 'Greek, Modern (1453-)',
    'kl-GL': 'Greenlandic',
    'gn-PY': 'Guarani',
    'gu-IN': 'Gujarati',
    'ht-HT': 'Haitian',
    'ha-NG': 'Hausa',
    'he-IL': 'Hebrew',
    'hz-NA': 'Herero',
    'hi-IN': 'Hindi',
    'ho-PG': 'Hiri Motu',
    'hu-HU': 'Hungarian',
    'is-IS': 'Icelandic',
    'io-FR': 'Ido',
    'ig-NG': 'Igbo',
    'id-ID': 'Indonesian',
    'ia-FR': 'Interlingua',
    ie: 'Interlingue',
    'iu-CA': 'Inuktitut',
    'ik-US': 'Inupiaq',
    'ga-IE': 'Irish',
    'it-IT': 'Italian',
    'it-CH': 'Italian (Switzerland)',
    'ja-JP': 'Japanese',
    'jv-ID': 'Javanese',
    'kn-IN': 'Kannada',
    'kr-NG': 'Kanuri',
    'ks-IN': 'Kashmiri',
    'kk-KZ': 'Kazakh',
    'km-KH': 'Khmer',
    'ki-KE': 'Kikuyu',
    'rw-RW': 'Kinyarwanda',
    'ky-KG': 'Kirghiz',
    'kv-RU': 'Komi',
    'kg-CD': 'Kongo',
    'ko-KR': 'Korean',
    'kj-AO': 'Kuanyama',
    'ku-IQ': 'Kurdish',
    'lo-LA': 'Lao',
    'la-VA': 'Latin',
    'lv-LV': 'Latvian',
    'lb-LU': 'Letzeburgesch',
    'li-NL': 'Limburgan',
    'ln-CD': 'Lingala',
    'lt-LT': 'Lithuanian',
    'lu-CD': 'Luba - Katanga',
    'mk-MK': 'Macedonian',
    'mg-MG': 'Malagasy',
    'ms-MY': 'Malay',
    'ml-IN': 'Malayalam',
    'mt-MT': 'Maltese',
    'gv-GB': 'Manx',
    'mi-NZ': 'Maori',
    'mr-IN': 'Marathi',
    'mh-MH': 'Marshallese',
    'es-MX': 'Mexican Spanish',
    'mo-MD': 'Moldavian',
    'mn-MN': 'Mongolian',
    'na-NR': 'Nauru',
    'nv-US': 'Navajo',
    'nd-ZW': 'Ndebele, North',
    'nr-ZA': 'Ndebele, South',
    'ng-NA': 'Ndonga',
    'ne-NP': 'Nepali',
    'se-NO': 'Northern Sami',
    'no-NO': 'Norwegian',
    'nb-NO': 'Norwegian Bokmal',
    'nn-NO': 'Norwegian Nynorsk',
    'oc-FR': 'Occitan (post 1500)',
    'oj-CA': 'Ojibwa',
    'or-IN': 'Oriya',
    'om-ET': 'Oromo',
    'os-GE': 'Ossetian',
    'pi-IN': 'Pali',
    'pa-IN': 'Panjabi',
    'fa-IR': 'Persian',
    'pl-PL': 'Polish',
    'pt-PT': 'Portuguese',
    'ps-AF': 'Pushto',
    'qu-PE': 'Quechua',
    'rm-CH': 'Raeto-Romance',
    'ro-RO': 'Romanian',
    'rn-BI': 'Rundi',
    'ru-RU': 'Russian',
    'sm-WS': 'Samoan',
    'sg-CF': 'Sango',
    'sa-IN': 'Sanskrit',
    'sc-IT': 'Sardinian',
    'gd-GB': 'Scottish Gaelic',
    'sr-SP': 'Serbian',
    'sn-ZW': 'Shona',
    'ii-CN': 'Sichuan Yi',
    'zh-CN': 'Simplified Chinese',
    'sd-PK': 'Sindhi',
    'si-LK': 'Sinhalese',
    'sk-SK': 'Slovak',
    'sl-SI': 'Slovenian',
    'so-SO': 'Somali',
    'st-LS': 'Sotho, Southern',
    'es-ES': 'Spanish',
    'su-ID': 'Sundanese',
    'sw-TZ': 'Swahili',
    'ss-SZ': 'Swati',
    'sv-SE': 'Swedish',
    'tl-PH': 'Tagalog',
    'ty-PF': 'Tahitian',
    'tg-TJ': 'Tajik',
    'ta-IN': 'Tamil',
    'tt-RU': 'Tatar',
    'te-IN': 'Telugu',
    'th-TH': 'Thai',
    'bo-CN': 'Tibetan',
    'ti-ET': 'Tigrinya',
    'to-TO': 'Tonga (Tonga Islands)',
    'zh-TW': 'Traditional Chinese',
    'ts-ZA': 'Tsonga',
    'tn-BW': 'Tswana',
    'tr-TR': 'Turkish',
    'tk-TM': 'Turkmen',
    'tw-GH': 'Twi',
    'ug-CN': 'Uighur',
    'uk-UA': 'Ukrainian',
    'ur-PK': 'Urdu',
    'uz-UZ': 'Uzbek',
    've-ZA': 'Venda',
    'vi-VN': 'Vietnamese',
    vo: 'Volapük',
    'wa-BE': 'Walloon',
    'cy-GB': 'Welsh',
    'wo-SN': 'Wolof',
    'xh-ZA': 'Xhosa',
    'yi-IL': 'Yiddish',
    'yo-NG': 'Yoruba',
    'za-CN': 'Zhuang',
    'zu-ZA': 'Zulu',
};

const SALUTATION = {
    '': '',
    DR: 'Dr.',
    MISS: 'Miss',
    MR: 'Mr.',
    MRS: 'Mrs.',
    MS: 'Ms.',
};

type LanguageKey = keyof typeof LANGUAGE;
type SalutationKey = keyof typeof SALUTATION;
type CountryKey = keyof typeof COUNTRY;
type State = (typeof STATE_PROVINCE)[keyof typeof STATE_PROVINCE];
type StateKey = KeysOfUnion<State>;

const REGEX = {
    password: /^(?=.*\d)(?=.*[A-Z])([\w\W\S]{9,})$/,
    phone: /^\+\d{11,15}$/,
    email: /^\w+@\w+\.\w+$/,
};

const DEFAULT_PHONE: Phone = { number: '', isPrimary: false };

const DEFAULT_ADDRESS: Address = {
    line1: '',
    line2: '',
    city: '',
    zip: '',
    state: '',
    isPrimary: false,
    country: '',
};

export type { StateKey, CountryKey, SalutationKey, LanguageKey };
export { COUNTRY, STATE_PROVINCE, LANGUAGE, REGEX, SALUTATION, DEFAULT_PHONE, DEFAULT_ADDRESS };
