name: Deploy to GCP Compute Engine (Production)

on:
  repository_dispatch:
    types: [deploy-production]

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Production
        id: deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP_PRD }} << 'EOF'
            cd /home/${{ secrets.GCP_USERNAME }}/Website
            
            LAST_COMMIT=$(git rev-parse --short HEAD)
            GIT_STATUS=$(git status -s)
            BUILD_STATUS="Success"

            git pull origin main || BUILD_STATUS="Git Pull Failed"
            npm install || BUILD_STATUS="NPM Install Failed"
            npm run build || BUILD_STATUS="Build Failed"

            SERVICES_STATUS=$(sudo systemctl status website-app | grep Active)
            
            sudo service website-app restart
            
            echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV
            echo "GIT_STATUS=$GIT_STATUS" >> $GITHUB_ENV
            echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_ENV
            echo "SERVICES_STATUS=$SERVICES_STATUS" >> $GITHUB_ENV
          EOF

      - name: Send Deployment Notification to Slack
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "text": "🚀 *Production Deployment*",
            "attachments": [
              {
                "fields": [
                  { "title": "Commit", "value": "${{ env.LAST_COMMIT }}", "short": true },
                  { "title": "Git Status", "value": "${{ env.GIT_STATUS }}", "short": true },
                  { "title": "Build Status", "value": "${{ env.BUILD_STATUS }}", "short": true },
                  { "title": "Service Status", "value": "${{ env.SERVICES_STATUS }}", "short": true }
                ]
              }
            ]
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
