name: Fetch PR Data & Trigger Deployment

on:
  push:
    branches:
      - main
      - staging

jobs:
  fetch-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get PR Details
        id: pr-details
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          PR_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=${{ github.ref_name }}")

          PR_NUMBER=$(echo "$PR_INFO" | jq -r '[.[] | select(.merged_at != null)][0].number')
          if [ -z "$PR_NUMBER" ]; then exit 1; fi

          PR_DETAILS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

          CREATOR=$(echo "$PR_DETAILS" | jq -r '.user.login')

          echo "creator=$CREATOR" >> $GITHUB_ENV

      - name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          event-type: ${{ github.ref_name == 'main' && 'deploy-production' || 'deploy-staging' }}
          client-payload: >
            {
              "creator": "${{ env.creator }}"
            }
